Class D3HGPortalEffect : Actor
{
	Default
	{
		+NOINTERACTION
	}
	States
	{
	Spawn:
		TNT1 A 1;
		Stop;
	}
}

Class D3Maledict : Actor
{
  int NumShots;
  int flight;
  int flightframe;
  int metonce;
  int flylandchance;
  int CeilingHeight;
  int flyclose;
  double distance;
  const wf = 4;
  const FlyTorchDist = 1600;
  int FlyTorchNums;
  int AttackChance;
  int Anger;
  Mixin SummonerFunctions;
Default
{
  Health 10000;
  Radius 50;
  Height 120;
  Scale 1;
  Mass 500000;
  Speed 12;
  MeleeRange 100;
  PainChance 10;
  PainChance "Fire", 0;
  PainChance "Burn", 0;
  PainChance "Flame", 0;
  damagefactor "BFG", 0.38;
  damagefactor "Plasma", 0.75;
  damagefactor "Freeze", .25;
  damagefactor "Ice", .25;
  damagefactor "Frost", .25;
  damagefactor "Disintegrate", .38;
  damagefactor "GreenFire", .38;
  damagefactor "Fire", .28;
  damagefactor "Burn", .28;
  damagefactor "Incinerate", .28;
  damagefactor "HKFT", 0.05;
  damagefactor "SSG", .75;
  damagefactor "Blast", .75;
  damagefactor "Cut", .75;
  damagefactor "Explosive", 1.5;
  damagefactor "Avoid", 0.0;
  damagefactor "killme", 0.0;
  damagefactor "Decaptate", 0.95;
  damagefactor "Head", 0.75;
  damagefactor "Stomp", 0.0;
  damagefactor "GibRemoving", 0.0;
  damagefactor "Trample", 0.0;
  damagefactor "TeleportRemover", 0.0;
  damagefactor "CauseObjectsToSplash", 0.0;
  PainChance "GloryFire", 255;
  PainChance "BloodPunch", 255;
  Monster;
  +DONTRIP;
  +SOLID;
  +DONTHARMSPECIES;
  +THRUSPECIES;
  +BOSS;
  +BOSSDEATH;
  +FLOORCLIP;
  +NORADIUSDMG;
  +DONTMORPH;
  +NODAMAGETHRUST;
  PainSound "D3Maledict/Pain";
  DeathSound "MLDD01";
  Obituary "%o could not stand up to the Hell Guardian.";

  PainChance "Taunt", 255;
  PainChance "Siphon", 255;
  PainChance "Cut", 2;
  PainChance "Saw", 2;
  PainChance "Disintegrate", 5;
  PainChance "IceExplosion", 50;
  PainChance "Ice", 20;
  PainChance "Frost", 20;
  PainChance "Explosive", 255;
  DropItem "Demonpickup2", 255;
  DropItem "Demonpickup2", 25;
  DropItem "DemonStrengthRune", 25;
  DropItem "Crucible", 50;
  WoundHealth 1000;
}

	action void A_PB_DropStormcastBossLoot()
	{
		let cv = CVar.FindCVar("pb_NoStormcastWeapon");
		if (cv && cv.GetInt() != 0)
			return;
		A_SpawnItemEx("Stormcast", 0, 0, 32, 0, 0, 0, random(0, 359), SXF_NOCHECKPOSITION);
	}

	void AngryAttack()
	{
		if(Self.Health > 0 && target && target.Health > 0 && CheckSight(target))
			{
			Anger = 128-((10000-(10000-self.health))*0.128);
			if (Anger > 128) {anger = 128;}
			AttackChance = random(0,256);
			if ( Anger >= AttackChance && TrDistance(self, target) > 100 )
				{SetState(FindState("Missile"));}
			else return;
			}
	}

	States
	{

	Wound:
		"####" "#" 1
		{
			if(GetCvar("be_ExecutionsON"))
			{
				if(countinv("FinisherToken")==0)
				{								
					A_SpawnItemEx("BaronHighlight",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_NOCHECKPOSITION);
					A_GiveInventory("FinisherToken",1);
				}
				
				if(GetCvar("be_MonsterStagger")==1)
				{
					bNOGRAVITY = false;
					return ResolveState("Stagger");
				}
				else
				{
					return ResolveState(null);
				}
			}
			return ResolveState(null);
		}
		Goto See;
	Stagger:
		D3MK A 0
		{
			if(getcvar("be_ExecutionHighlight")==1)
			{	return ResolveState("PrepareStaggerHighlight");}
			else
			{	return ResolveState("StagLooper");	}
		}
		Goto StagLooper;
	PrepareStaggerHighlight:
		D3MK A 0;
		Goto StagLooper;
	
	StagLooper:
		"####" "#" 4
		{
			if(!countinv("FinisherToken"))
			{
				if (flight > 0)
					{bNOGRAVITY = true;}
				return ResolveState("See");
			}
			if(getcvar("be_NoisyStagger") && countinv("PainSoundToken"))
			{ 
				A_Pain(); 
				A_TakeInventory("PainSoundToken");
			}
			return ResolveState(null);
		}
		"####" "#" 0;
		Loop;

	Death.Crucible:
		TNT1 A 0 A_SpawnItemEx("GloryHightPinataSpawn2",0,0,Height / 2,random(0,8),0,random(0,8),random(0,360));
	Goto Death.cut;

	Pain.GloryFire:
		TNT1 A 0 A_Jump(192, "See");
		TNT1 A 0 A_SpawnItemEx("FlamePinataSpawn",0,0,Height / 2,random(0,8),0,random(0,8),random(0,360));
	Goto Pain;
		
	Death.GloryFire:
		TNT1 A 0 A_SpawnItemEx("FlamePinataSpawn",0,0,Height / 2,random(0,8),0,random(0,8),random(0,360));
	Goto Death.Fire;
   
	Death.BloodPunch:
		TNT1 A 0	A_GiveToTarget("BloodPunchKilled",1);
		TNT1 A 0	A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0	A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0	A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0	A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0	A_SpawnItemEx("GloryHightPinataSpawn2",0,0,Height / 2,random(0,8),0,random(0,8),random(0,360));
	Goto Death;
   
	Pain.BloodPunch:
		TNT1 A 0	A_GiveToTarget("BloodPunchKilled",1);
		TNT1 A 0	A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0	A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0	A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0	A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
	Goto Pain;


	Spawn:
		TNT1 A 0;
		TNT1 A 0 {Height = 160;}
		TNT1 A 0 A_StartSound("MLDSTLP", CHAN_BODY);
		D3MB B 52 A_Look;
		D3MB A 76 A_Look;
		D3MB B 60 A_Look;
		D3MB A 74 A_Look;
	Loop;

	See:
		TNT1 A 0;
		TNT1 A 0 A_ScaleVelocity(0);
		TNT1 A 0
		{
		if (flight == 1 && metonce == 1)
			{
			return ResolveState("FloatLoop");
			}
		else
			{
			return ResolveState(null);
			}
		}

		TNT1 A 0
		{
		if (flight == 2 && metonce == 1)
			{
			return ResolveState("DragonAttackReload");
			}
		else
			{
			return ResolveState(null);
			}
		}


		TNT1 A 0
		{
		if (flight == 0 && metonce == 1)
			{
			return ResolveState("SeeContinue");
			}
		else
			{
			return ResolveState(null);
			}
		}

		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 {Height = 120;}
		TNT1 A 0 {metonce = 1;}
		D3MB BCD 7;
		TNT1 A 0 A_StartSound("MLDAC02", CHAN_BODY, CHANF_OVERLAP);
		D3MB EF 7;
		TNT1 A 0 A_StartSound("MLDAC01", CHAN_BODY, CHANF_OVERLAP);
		D3MB GFGFGFGFGFGF 5;
		D3MB F 9;
		D3MB GFGF 5;
		TNT1 A 0 A_StartSound("MLDAC02", CHAN_BODY, CHANF_OVERLAP);
		D3MB HIJK 6;
		D3MA E 6;
	SeeContinue:
		TNT1 A 0;
		TNT1 A 0 {flylandchance = flylandchance+2;}
		TNT1 A 0 {Height = 120; Speed = 12; bFRIGHTENED = false;}
		TNT1 A 0 A_Jump( flight ==1, "FloatLoop");
		TNT1 A 0 A_Jump( flight ==2, "FloatLoop");
		TNT1 A 0 AngryAttack();
		TNT1 A 0 A_StartSound("D3Maledict/Step", CHAN_BODY, CHANF_OVERLAP);
		D3MA A 2 A_Chase;
		D3MA AA 4 A_Chase;
		D3MA A 2 A_Chase;
		D3MA BBB 4 A_Chase;
		TNT1 A 0 A_StartSound("D3Maledict/Step", CHAN_BODY, CHANF_OVERLAP);
		D3MA C 2 A_Chase;
		D3MA CC 4 A_Chase;
		D3MA C 2 A_Chase;
		D3MA DDD 4 A_Chase;
		TNT1 A 0 A_Jump(flylandchance, "TakeOff");
	Loop;


	TakeOff:
		TNT1 A 0;
		TNT1 A 0 {CeilingHeight = int(CeilingZ - FloorZ);}
		TNT1 A 0
				{
				if (CeilingHeight < 280)
					{
					if (flylandchance > 256) {flylandchance = 256;}
					return ResolveState("SeeContinue");
					}
				else
					{
					return ResolveState(null);
					}
				}

		TNT1 A 0 {bNOPAIN = true;}
		TNT1 A 0 {flylandchance = 0;}
		D3MA A 2;
		D3ME ABC 2;
		D3ME C 6;
		TNT1 A 0 A_StartSound("MLDFL01", CHAN_BODY, CHANF_OVERLAP);
		D3ME D 2;
		D3MC DEEFF 2 {ThrustThingZ(0, 20, 0, 0);}
		TNT1 A 0 A_ScaleVelocity(0);
		TNT1 A 0
		{
		bNOGRAVITY = true;
		bFLOAT = true;
		bNOPAIN = false;
		bFRIGHTENED = false;
		flight = 1;
		}
		D3MC GHIJKL 2;

	FloatLoop:
		TNT1 A 0;
		TNT1 A 0 {flylandchance = flylandchance+2;}
		TNT1 A 0 A_JumpIf( flight == 2, "DragonAttackReload");
		TNT1 A 0 {Height = 250; Speed = 20; bFRIGHTENED = false;  flight = 1;}
		TNT1 A 0 A_ScaleVelocity(0);
		TNT1 A 0 AngryAttack();

	TNT1 A 0 
		{
			if (FlightFrame == 0)
			{
				return ResolveState("FloatLoopS1");
			}
			else if (FlightFrame == 1)
			{
				return ResolveState("FloatLoopS2");
			}
			else if (FlightFrame == 2)
			{
				return ResolveState("FloatLoopS3");
			}
			else if (FlightFrame == 3)
			{
				return ResolveState("FloatLoopS4");
			}
			else if (FlightFrame == 4)
			{
				return ResolveState("FloatLoopS5");
			}
			else if (FlightFrame == 5)
			{
				return ResolveState("FloatLoopS6");
			}
			else if (FlightFrame == 6)
			{
				return ResolveState("FloatLoopS7");
			}
			else if (FlightFrame == 7)
			{
				return ResolveState("FloatLoopS8");
			}
			else if (FlightFrame == 8)
			{
				return ResolveState("FloatLoopS9");
			}
			else if (FlightFrame == 9)
			{
				return ResolveState("FloatLoopS10");
			}
			else if (FlightFrame == 10)
			{
				return ResolveState("FloatLoopS11");
			}
			else if (FlightFrame == 11)
			{
				return ResolveState("FloatLoopS0");
			}
			else
			{
				return ResolveState(null);
			}
		}

	FloatLoopS0:
		TNT1 A 0 {FlightFrame=0; A_StartSound("D3Maledict/float", CHAN_BODY, CHANF_OVERLAP);}
		D3MC A WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS1:
		D3MC B WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS2:
		D3MC C WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS3:
		D3MC D WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS4:
		D3MC E WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS5:
		D3MC F WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS6:
		D3MC G WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS7:
		D3MC H WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS8:
		D3MC I WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS9:
		D3MC J WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS10:
		D3MC K WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	FloatLoopS11:
		D3MC L WF {FlightFrame++;}
		TNT1 A 0 A_Chase;

		TNT1 A 0 A_Jump(flylandchance, "LandingStart");
		TNT1 A 0 {distance = TrDistance(self, target);}
		TNT1 A 0 A_JumpIf(distance > 1000, "PrepareDragonAttack");

	Goto FloatLoop;
	
	LandingStart:
		TNT1 A 0;
		TNT1 A 0 {flylandchance = 0;}
		TNT1 A 0 A_ScaleVelocity(0);
	Goto landing;

	Landing:
		TNT1 A 0;
		TNT1 A 0 {bNOPAIN = true;}
		TNT1 A 0 A_Jump(256, FlightFrame);
		D3MC ABCDEFGHIJKL 4;

		TNT1 A 0
		{
		bNOGRAVITY = false;
		bFLOAT = false;
		bTHRUACTORS = true;
		flight = 0;
		}
		
	LandingContinue:
		D3MC A 2 A_CheckFloor("LandingEnd");
		TNT1 A 0
		{
		if(waterlevel >= 1) {SetState(FindState("LandingEnd"));}
		}
	Loop;
	LandingEnd:
		TNT1 A 0 A_StartSound("MLDFL02", CHAN_BODY, CHANF_OVERLAP);
		TNT1 A 0 Radius_Quake (6, 35, 0, 22, 0);
		D3MC BC 2;
		D3ME DCBA 2;
		TNT1 A 0 {
		bTHRUACTORS = false;
		bNOPAIN = false;
		}


		TNT1 A 0
			{
			Vector2 move = AngleToVector(0, radius*1.5);
			Vector2 ptry = self.pos.xy + move;
			if (!self.TryMove(ptry, height))
				{
				return ResolveState("TakeOff");
				}
			else
				{
				return ResolveState(null);
				}
			}

		TNT1 A 0 
				{
				if (TestMobjLocation() == false)
				{
				return ResolveState("TakeOff");
				}
			else
				{
				return ResolveState(null);
				}
			}

	Goto SeeContinue;

	Melee:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf( flight == 1, "PrepareAttackFloat");
		TNT1 A 0 {
				if (flight == 2)
					{
					FlyTorchNums = 0;
					Flight = 1;
					bFRIGHTENED = false;
					FlyClose = 1;
					return ResolveState("DragonAttack");
					}
				else
					{
					return ResolveState(null);
					}
				}


		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 {bSPRITEFLIP = random(0,1);}
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_StartSound("MLDBT01");
		D3MA EFG 4;
		D3MA G 7;
		D3MA H 4;
		TNT1 A 0 A_CustomMeleeAttack(80, "", "", "BHFT");
		D3MA I 4;
		D3MA JKE 4;
		TNT1 A 0 {bSPRITEFLIP = false;}
	Goto SeeContinue;

	AttackFloatNoSummon:
		TNT1 A 0;
		TNT1 A 0 A_Jump(256, "FireBAllsFloat", "PrepareDragonAttack");
	Goto FloatLoop;


	PrepareAttackFloat:
		TNT1 A 0;
		TNT1 A 0 A_Jump(80, "PrepareDragonAttack");
		TNT1 A 0 A_Jump(256, FlightFrame);
		D3MC ABCDEFGHIJKL WF A_FaceTarget;

		TNT1 A 0 {NumShots = 0;}
		TNT1 A 0 {distance = TrDistance(self, target);}

		TNT1 A 0 A_JumpIf(distance < 400, "TorchFloat");
		TNT1 A 0 A_Jump(256, "FireBAllsFloat", "SummonFloat", "CastMeteorsFloat");

	FireBallsFloat:
		TNT1 A 0;
		TNT1 A 0 A_StartSound("D3Maledict/float", CHAN_BODY, CHANF_OVERLAP);
		TNT1 A 0 A_FaceTarget;
		D3MC M WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
		D3MC N WF A_SpawnProjectile("NewImpBall", 250, 0, 0, 0);
		TNT1 A 0 A_FaceTarget;
		D3MC O WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
		D3MC P WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
		D3MC Q WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
		D3MC R WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
		D3MC S WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
		D3MC T WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
		D3MC U WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
		D3MC V WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
		D3MC W WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
		D3MC X WF A_SpawnProjectile("NewImpBall", 250, 0, random(-5,5), CMF_OFFSETPITCH, random(-3,3));
		TNT1 A 0 A_FaceTarget;
	Goto FloatLoop;



	TorchFloat:
		TNT1 A 0;

	TNT1 A 0 
		{
			if (FlightFrame == 1)
			{
				return ResolveState("TorchFloatS1");
			}
			else if (FlightFrame == 2)
			{
				return ResolveState("TorchFloatS2");
			}
			else if (FlightFrame == 3)
			{
				return ResolveState("TorchFloatS3");
			}
			else if (FlightFrame == 4)
			{
				return ResolveState("TorchFloatS4");
			}
			else if (FlightFrame == 5)
			{
				return ResolveState("TorchFloatS5");
			}
			else if (FlightFrame == 6)
			{
				return ResolveState("TorchFloatS6");
			}
			else if (FlightFrame == 7)
			{
				return ResolveState("TorchFloatS7");
			}
			else if (FlightFrame == 8)
			{
				return ResolveState("TorchFloatS8");
			}
			else if (FlightFrame == 9)
			{
				return ResolveState("TorchFloatS9");
			}
			else if (FlightFrame == 10)
			{
				return ResolveState("TorchFloatS10");
			}
			else if (FlightFrame == 11)
			{
				return ResolveState("TorchFloatS11");
			}

			else
			{
				return ResolveState(null);
			}
		}
	
		TNT1 A 0 A_StartSound("D3Maledict/float", CHAN_BODY, CHANF_OVERLAP);
		TNT1 A 0 A_FaceTarget;
		D3MC M WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC M WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS1:
		TNT1 A 0 A_FaceTarget;
		D3MC N WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC N WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS2:
		TNT1 A 0 A_FaceTarget;
		D3MC O WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC O WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS3:
		TNT1 A 0 A_FaceTarget;
		D3MC P WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC P WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS4:
		TNT1 A 0 A_FaceTarget;
		D3MC Q WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC Q WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS5:
		TNT1 A 0 A_FaceTarget;
		D3MC R WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC R WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS6:
		TNT1 A 0 A_FaceTarget;
		D3MC S WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC S WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS7:
		TNT1 A 0 A_FaceTarget;
		D3MC T WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC T WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS8:
		TNT1 A 0 A_FaceTarget;
		D3MC U WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC U WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS9:
		TNT1 A 0 A_FaceTarget;
		D3MC V WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC V WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS10:
		TNT1 A 0 A_FaceTarget;
		D3MC W WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC W WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

	TNT1 A 0 {FlightFrame ++;}
	TorchFloatS11:
		TNT1 A 0 A_FaceTarget;
		D3MC X WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MC X WF/2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 250, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 {FlightFrame = 0;}
		TNT1 A 0 {NumShots = NumShots+1;}
		TNT1 A 0 A_JumpIf(NumShots < 2, "TorchFloat");
	Goto FloatLoop;


		//A-L - mouth closed, M-X - opened
	SummonFloat:
		TNT1 A 0;
		TNT1 A 0 CountReinforcements("PB_LostSoul", GetCVar("D3MaledictLSCount"), "AttackFloatNoSummon");
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_StartSound("MLDSPLS1", CHAN_BODY);

		TNT1 A 0 A_StartSound("D3Maledict/float", CHAN_BODY, CHANF_OVERLAP);
		D3MC ABOPEF WF A_FaceTarget;
		TNT1 A 0 SpawnReinforcement("PB_LostSoul",0, 90, 60, self, self, target, "SkullAttack", 0, 0, "D3Maledict", 1, 0, 0);
		TNT1 A 0 A_SpawnItemEx ("SeekersTeleportEffect", 0, 90, 30, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		D3MC STIJWX WF A_FaceTarget;
		TNT1 A 0 SpawnReinforcement("PB_LostSoul",0, -90, 60, self, self, target, "SkullAttack", 0, 0, "D3Maledict", 1, 0, 0);
		TNT1 A 0 A_SpawnItemEx ("SeekersTeleportEffect", 0, -90, 30, 0, 0, 0, 0, SXF_NOCHECKPOSITION);

		TNT1 A 0 A_StartSound("D3Maledict/float", CHAN_BODY, CHANF_OVERLAP);
		D3MC ABOPEF WF A_FaceTarget;
		TNT1 A 0 SpawnReinforcement("PB_LostSoul",0, 90, 60, self, self, target, "SkullAttack", 0, 0, "D3Maledict", 1, 0, 0);
		TNT1 A 0 A_SpawnItemEx ("SeekersTeleportEffect", 0, 90, 30, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		D3MC STIJWX WF A_FaceTarget;
		TNT1 A 0 SpawnReinforcement("PB_LostSoul",0, -90, 60, self, self, target, "SkullAttack", 0, 0, "D3Maledict", 1, 0, 0);
		TNT1 A 0 A_SpawnItemEx ("SeekersTeleportEffect", 0, -90, 30, 0, 0, 0, 0, SXF_NOCHECKPOSITION);

		TNT1 A 0 A_StartSound("D3Maledict/float", CHAN_BODY, CHANF_OVERLAP);
		D3MC ABOPEF WF A_FaceTarget;
		TNT1 A 0 SpawnReinforcement("PB_LostSoul",0, 90, 60, self, self, target, "SkullAttack", 0, 0, "D3Maledict", 1, 0, 0);
		TNT1 A 0 A_SpawnItemEx ("SeekersTeleportEffect", 0, 90, 30, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		D3MC STIJWX WF A_FaceTarget;

	Goto FloatLoop;

	CastMeteorsFloat:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_StartSound("MLDSPLA1", CHAN_BODY);
		D3MC MNOP WF A_FaceTarget;
		D3MC E WF A_FaceTarget;
		D3MC E WF/2 A_FaceTarget;
		TNT1 A 0 A_StartSound("MLDSPLA2", CHAN_BODY, CHANF_OVERLAP);
		D3MC R WF/2 A_FaceTarget;
		D3MC STU WF A_FaceTarget;
		TNT1 A 0 A_SpawnItemEx("Shul", 60, 0, 220);
		TNT1 AAAAAAAAA 0 A_SpawnItemEx("ObeliskTrailSpark", 60, random(-5,5), random(215,225), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SpawnProjectile ("MaledictCometAttack",28,0,0,0);
		D3MC JKL 4 A_FaceTarget;
	Goto FloatLoop;

	DragonAttackReload:
		TNT1 A 0;
		TNT1 A 0 {FlyClose = 0;}
		TNT1 A 0 {FlyTorchNums = FlyTorchNums - 1;}
		TNT1 A 0 {CeilingHeight = int(CeilingZ - FloorZ);}
		TNT1 A 0 {
				if (FlyTorchNums < 1)
					{
					if (CeilingHeight >= 120)
						{
						FlyTorchNums = 0;
						Flight = 1;
						return ResolveState("DragonFlyLoopEnd");
						}
					else
						{
						return ResolveState("PrepareDragonAttack");
						}
					}
				else
					{
					return ResolveState(null);
					}
				}
		TNT1 A 0 A_Jump(256, "PrepareDragonAttack2");

	DragonFlyLoopEnd:
		TNT1 A 0;
		TNT1 A 0
				{
				FlyTorchNums = 0;
				Flight = 1;
				bFRIGHTENED = false;
				bNOPAIN = false;
				}
		D3MA U 4 ThrustThing(0, 3, 0);
		D3MA U 4 ThrustThing(0, 2, 0);
		D3MA U 4 ThrustThing(0, 1, 0);
		TNT1 A 0 A_ScaleVelocity(0);
	Goto FloatLoop;


	DragonFlyLoopEndToTorch:
		TNT1 A 0;
		TNT1 A 0 {bNOPAIN = false;}
		TNT1 A 0
				{
				FlyTorchNums = 0;
				Flight = 1;
				bFRIGHTENED = false;
				}
		D3MA U 4 ThrustThing(0, 3, 0);
		D3MA U 4 ThrustThing(0, 2, 0);
		D3MA U 4 ThrustThing(0, 1, 0);
		TNT1 A 0 A_ScaleVelocity(0);
	Goto TorchFloat;


	PrepareDragonAttack:
		TNT1 A 0;
		TNT1 A 0 {Flight = 2; FlyTorchNums = random(1, 3); bNOPAIN = true;}
	PrepareDragonAttack2:
		TNT1 A 0 {bFRIGHTENED = true;}
		TNT1 A 0 A_ScaleVelocity(0);
		TNT1 A 0 {Height = 80; Speed = 40;}
		TNT1 A 0 {NumShots = 0;}
	DragonFlyLoopStart:
		D3MA O 4;
	DragonFlyLoop:
		TNT1 A 0;
		TNT1 A 0 {bNOPAIN = true;}
		TNT1 A 0 A_Jump(256, FlightFrame);
	DragonFlyLoopContinue:
		TNT1 A 0 {FlightFrame = 0; distance = TrDistance(self, target);}	
		TNT1 A 0 {
		if (distance <= 100 || 120 >= int(CeilingZ - FloorZ))
					{
					FlyTorchNums = 0;
					Flight = 1;
					bFRIGHTENED = false;
					return ResolveState("DragonFlyLoopEndToTorch");
					}
				else
					{
					A_StartSound("D3Maledict/fastfloat", CHAN_BODY, CHANF_OVERLAP);
					return ResolveState(null);
					}
			}

		D3MD A WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS1:
		D3MD B WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS2:
		D3MD C WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS3:
		D3MD D WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS4:
		D3MD E WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS5:
		D3MD F WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS6:
		D3MD G WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS7:
		D3MD H WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS8:
		D3MD I WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS9:
		D3MD J WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS10:
		D3MD K WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
	DragonFlyLoopS11:
		D3MD L WF {FlightFrame++;}
		TNT1 A 0 A_Chase;
		TNT1 A 0 {NumShots = NumShots+1;}


		TNT1 A 0 {distance = TrDistance(self, target);}
		TNT1 A 0 {if (NumShots > 0 || distance < 100)	{bFRIGHTENED = false;}	}
		TNT1 A 0 A_JumpIf(NumShots < 2, "DragonFlyLoopContinue");
		TNT1 A 0 A_JumpIf(distance > 1200, "DragonFlyLoopContinue");
		TNT1 A 0 A_CheckSight("DragonFlyLoopContinue");
		TNT1 A 0 A_Jump(256, "DragonAttack");


	DragonAttack:
		TNT1 A 0;
		TNT1 A 0 {Height = 70; Speed = 50; bFRIGHTENED = false; bNOPAIN = true;}
		TNT1 A 0 A_StartSound("D3Maledict/fastfloat", CHAN_BODY, CHANF_OVERLAP);
		TNT1 A 0 A_FaceTarget;
		D3MD M WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD M WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

		TNT1 A 0 A_FaceTarget;
		D3MD N WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD N WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}


		TNT1 A 0 A_FaceTarget;
		D3MD O WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD O WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}


		TNT1 A 0 A_FaceTarget;
		D3MD P WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD P WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}


		TNT1 A 0 A_FaceTarget;
		D3MD Q WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD Q WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}


		TNT1 A 0 A_FaceTarget;
		D3MD R WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD R WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}


		TNT1 A 0 A_FaceTarget;
		D3MD S WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD S WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}


		TNT1 A 0 A_FaceTarget;
		D3MD T WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD T WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}


		TNT1 A 0 A_FaceTarget;
		D3MD U WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD U WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}


		TNT1 A 0 A_FaceTarget;
		D3MD V WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD V WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}


		TNT1 A 0 A_FaceTarget;
		D3MD W WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD W WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}


		TNT1 A 0 A_FaceTarget;
		D3MD X WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 A_FaceTarget;
		D3MD X WF/2
		{
		if (FlyClose == 0) {A_SkullAttack(15);}
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 50, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}

		TNT1 A 0 A_ScaleVelocity(0);


	Goto DragonAttackReload;
		

	AttackLandNoSummon:
		TNT1 A 0;
		TNT1 A 0 A_Jump(256, "FireBallsLand", "CastMeteorsLand");
	Goto SeeContinue;

	Missile:
		TNT1 A 0;
		TNT1 A 0 A_Jumpif(flight == 1, "PrepareAttackFloat");
		TNT1 A 0 A_JumpIf( flight == 2, "DragonFlyLoop");		
		TNT1 A 0 {NumShots = 0;}
		TNT1 A 0 {distance = TrDistance(self, target);}

		TNT1 A 0 A_JumpIf(distance > 4000, "SeeContinue");
		TNT1 A 0 A_JumpIf(distance < 400, "TorchLand");

		TNT1 A 0 {CeilingHeight = int(CeilingZ - FloorZ);}
		TNT1 A 0 A_JumpIf(CeilingHeight < 260, "FireBallsLand");

		TNT1 A 0 A_Jump(256, "FireBallsLand", "SummonLand", "CastMeteorsLand");



	SummonLand:
		TNT1 A 0;
		TNT1 A 0 CountReinforcements("PB_LostSoul", GetCVar("D3MaledictLSCount"), "AttackLandNoSummon");
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_StartSound("MLDSPLS1", CHAN_BODY);
		D3MA LMNO 6 A_FaceTarget;
		TNT1 A 0 {Height = 250;}
		TNT1 A 0 SpawnReinforcement("PB_LostSoul",0, -90, 60, self, self, target, "SkullAttack", 0, 0, "D3Maledict", 1, 0, 0);
		TNT1 A 0 A_SpawnItemEx ("SeekersTeleportEffect", 0, -90, 30, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		D3MA S 18 A_FaceTarget;
		D3MA T 13 A_FaceTarget;
		D3MA S 4 A_FaceTarget;
		D3MA T 18 A_FaceTarget;
		D3MA S 6 A_FaceTarget;
		TNT1 A 0 SpawnReinforcement("PB_LostSoul",0, 90, 60, self, self, target, "SkullAttack", 0, 0, "D3Maledict", 1, 0, 0);
		TNT1 A 0 A_SpawnItemEx ("SeekersTeleportEffect", 0, 90, 30, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		D3MA T 10 A_FaceTarget;
		D3MA S 13 A_FaceTarget;
		D3MA T 7 A_FaceTarget;
		TNT1 A 0 SpawnReinforcement("PB_LostSoul",0, -90, 60, self, self, target, "SkullAttack", 0, 0, "D3Maledict", 1, 0, 0);
		TNT1 A 0 A_SpawnItemEx ("SeekersTeleportEffect", 0, -90, 30, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		D3MA S 12 A_FaceTarget;
		D3MA T 4 A_FaceTarget;
		D3MA S 4 A_FaceTarget;
		TNT1 A 0 SpawnReinforcement("PB_LostSoul",0, 90, 60, self, self, target, "SkullAttack", 0, 0, "D3Maledict", 1, 0, 0);
		TNT1 A 0 A_SpawnItemEx ("SeekersTeleportEffect", 0, 90, 30, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		D3MA T 9 A_FaceTarget;
		D3MA S 4 A_FaceTarget;
		D3MA T 10 A_FaceTarget;
		D3MA S 6 A_FaceTarget;
		D3MA T 7 A_FaceTarget;
		TNT1 A 0 SpawnReinforcement("PB_LostSoul",0, -90, 60, self, self, target, "SkullAttack", 0, 0, "D3Maledict", 1, 0, 0);
		TNT1 A 0 A_SpawnItemEx ("SeekersTeleportEffect", 0, -90, 60, 0, 0, 0, 0, SXF_NOCHECKPOSITION);
		D3MA S 15 A_FaceTarget;
		D3MA ONML 6 A_FaceTarget;
	Goto SeeContinue;


	CastMeteorsLand:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		D3MA LMNO 6 A_FaceTarget;
		TNT1 A 0 {Height = 250;}
		TNT1 A 0 A_StartSound("MLDSPLA1", CHAN_BODY);
		D3MA T 15 A_FaceTarget;
		D3MA S 6 A_FaceTarget;
		TNT1 A 0 A_StartSound("MLDSPLA2", CHAN_BODY, CHANF_OVERLAP);
		D3MA T 6 A_FaceTarget;
		D3MA S 3 A_FaceTarget;
		TNT1 A 0 A_SpawnItemEx("Shul", 60, 0, 160);
		TNT1 AAAAAAAAA 0 A_SpawnItemEx("ObeliskTrailSpark", 60, random(-5,5), random(155,165), 0, 0, 0, 0, 128, 0);
		TNT1 A 0 A_SpawnProjectile ("MaledictCometAttack",28,0,0,0);
		D3MA T 36 A_FaceTarget;
		D3MA ONML 6 A_FaceTarget;
	Goto SeeContinue;


	FireBallsLand:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		D3MA LMNOP 6 A_FaceTarget;
		TNT1 A 0 {Height = 250;}
	FireBallsLandContinue:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		D3MA Q 4
		{
		A_SpawnProjectile("NewImpBall", 60, 0, 0, 0);
		A_SpawnProjectile("NewImpBall", 60, 0, random(-15,15), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("NewImpBall", 60, 0, random(-15,15), CMF_OFFSETPITCH, random(-3,3));
		}
		
		TNT1 A 0 {NumShots = NumShots+1;}
		TNT1 A 0 A_JumpIf(NumShots < 5, "FireBallsLandContinue");
		TNT1 A 0 A_Jump(256, "LandFireBreathEnd");

	TorchLand:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		D3MA LMNOP 6 A_FaceTarget;
	TorchLandContinue:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		D3MA Q 2
		{
		A_SpawnProjectile("MaledictFlamethrowerMissile", 60, 0, 0, 0);
		A_SpawnProjectile("MaledictFlamethrowerMissile", 60, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		A_SpawnProjectile("MaledictFlamethrowerMissile", 60, 0, random(-10,10), CMF_OFFSETPITCH, random(-3,3));
		}
		TNT1 A 0 {NumShots = NumShots+1;}
		TNT1 A 0 A_JumpIf(NumShots < 30, "TorchLandContinue");



	LandFireBreathEnd:
		D3MA RL 6;
	Goto SeeContinue;
	
	Pain:
		TNT1 A 0 A_StopSound(CHAN_BODY);
		TNT1 A 0 A_JumpIf (Flight == 1, "PainFloat");
		D3MF K 4;
		D3MF K 4 A_Pain;
	Goto SeeContinue;


	PainFloat:
		TNT1 A 0;
		TNT1 A 0 
			{
			if (FlightFrame == 0)
			{
				return ResolveState("PainFloatS1");
			}
			else if (FlightFrame == 1)
			{
				return ResolveState("PainFloatS2");
			}
			else if (FlightFrame == 2)
			{
				return ResolveState("PainFloatS3");
			}
			else if (FlightFrame == 3)
			{
				return ResolveState("PainFloatS4");
			}
			else if (FlightFrame == 4)
			{
				return ResolveState("PainFloatS5");
			}
			else if (FlightFrame == 5)
			{
				return ResolveState("PainFloatS6");
			}
			else if (FlightFrame == 6)
			{
				return ResolveState("PainFloatS7");
			}
			else if (FlightFrame == 7)
			{
				return ResolveState("PainFloatS8");
			}
			else if (FlightFrame == 8)
			{
				return ResolveState("PainFloatS9");
			}
			else if (FlightFrame == 9)
			{
				return ResolveState("PainFloatS10");
			}
			else if (FlightFrame == 10)
			{
				return ResolveState("PainFloatS11");
			}
			else if (FlightFrame == 11)
			{
				return ResolveState("PainFloatS0");
			}
			else
			{
				return ResolveState(null);
			}
		}

	PainFloatS0:
		TNT1 A 0;
		TNT1 A 0 {NumShots = 0;}
		TNT1 A 0 {FlightFrame=0; A_StartSound("D3Maledict/float", CHAN_BODY, CHANF_OVERLAP);}
		D3MG A WF;
		TNT1 A 0 A_Pain;
	PainFloatS1:
		D3MG B WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	PainFloatS2:
		D3MG C WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	PainFloatS3:
		D3MG D WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	PainFloatS4:
		D3MG E WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	PainFloatS5:
		D3MG F WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	PainFloatS6:
		TNT1 A 0 A_Pain;
		D3MG G WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	PainFloatS7:
		D3MG H WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	PainFloatS8:
		D3MG I WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	PainFloatS9:
		D3MG J WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	PainFloatS10:
		D3MG K WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	PainFloatS11:
		D3MG L WF;
		TNT1 A 0 {FlightFrame++; NumShots++;}
		TNT1 A 0 A_JumpIf(NumShots > 3, "FloatLoop");
	Goto FloatLoop;


	Death:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_JumpIfIntargetInventory("SSGSelected", 1, "Death.SSG");
		TNT1 A 0 A_JumpIfIntargetInventory("MinigunSelected", 1, "Death.Railgun");
		TNT1 A 0 A_JumpIfIntargetInventory("NewChaingunSelected", 1, "Death.Railgun");
		TNT1 A 0 A_JumpIfIntargetInventory("MG42Selected", 1, "Death.Railgun");
		TNT1 A 0 A_JumpIfIntargetInventory("QSGSelected", 1, "Death.SSG");

		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
		TNT1 A 0 A_StartSound("MLDD01");
		TNT1 A 0 A_JumpIf(Flight == 1, 7);
		TNT1 A 0 A_JumpIf(Flight == 2, 8);
		D3MF LMNO 6;
		D3MF P 8;
		D3MF QR 7;
		D3MF STUV 6;
	FallLoop:
		D3MF V 1 A_CheckFloor("SpawnCorpse");
	Loop;

	SpawnCorpse:
		TNT1 A 0 A_StartSound("Corpse/Fall",CHAN_6);
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadD3Maledict");
	Stop;


	Death.SSG:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile ("XDeathWingD3Maledict", 91, -24, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathWingD3Maledict", 91, 24, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile("XDeathHeadD3Maledict", 90, -55, random (10, 15), 2, random (80, 90));
		TNT1 A 0 A_SpawnProjectile ("XDeathHumpD3Maledict", 80, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAA 0 A_SpawnItem("Muchblood2");
		TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 55, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAA 0 A_SpawnItemEX("NashgoreGibs", 0, 0, 0, random (4, 12), 0, random (4, 12), random(0, 360));
		TNT1 AA 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 52, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 52, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 52, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 52, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodFaster", 52, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodMuchFaster", 52, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("SuperWallRedBlood", 52, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("SuperWallRedBlood", 56, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("BloodMistBig", 50, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_Jump(256, "HalfSelect");


	Death.Railgun:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
		TNT1 AAAAA 0 A_SpawnItemEX("NashgoreGibs", 50, 0, 0, random (4, 12), 0, random (4, 12), random(0, 360));
		TNT1 AAA 0 A_SpawnProjectile ("MeatDeathsmall", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 52, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("RipHalfD3MaledictUpper", 60, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 Bright A_SpawnItem ("Big_Blood", 0, 30);
	HalfSelect:
		TNT1 A 0;
		TNT1 A 0
		{
		if (Flight == 0)
				{A_SpawnItemEx ("RipHalfD3MaledictLower1",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		if (Flight == 1)
				{A_SpawnItemEx ("RipHalfD3MaledictLower2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		if (Flight == 2)
				{A_SpawnItemEx ("RipHalfD3MaledictLower3",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		}
	Stop;



	Death.Incinerate:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
		TNT1 A 0
		{
		if (Flight == 0)
				{A_SpawnItemEx ("IncinerateDyingD3Maledict1",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		if (Flight == 1)
				{A_SpawnItemEx ("IncinerateDyingD3Maledict2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		if (Flight == 2)
				{A_SpawnItemEx ("IncinerateDyingD3Maledict3",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		}
	Stop;


	Death.Disintegrate:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
		TNT1 A 0
		{
		if (Flight == 0)
				{A_SpawnItemEx ("DisintegrateDyingD3Maledict1",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		if (Flight == 1)
				{A_SpawnItemEx ("DisintegrateDyingD3Maledict2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		if (Flight == 2)
				{A_SpawnItemEx ("DisintegrateDyingD3Maledict3",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		}
	Stop;

	Death.Plasma:
	Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
		TNT1 A 0
		{
		if (Flight == 0)
				{A_SpawnItemEx ("PlasmaDyingD3Maledict1",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		if (Flight == 1)
				{A_SpawnItemEx ("PlasmaDyingD3Maledict2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		if (Flight == 2)
				{A_SpawnItemEx ("PlasmaDyingD3Maledict3",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		}
	Stop;



	Death.Saw:
	Death.Cut:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
		TNT1 A 0 A_StartSound("MLDD01");
		TNT1 A 0 A_JumpIf(Flight == 1, "DeathNoHead1");
		TNT1 A 0 A_JumpIf(Flight == 2, "DeathNoHead2");
		TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 90, -55, random (0, 360), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 90, -55, random (0, 360), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_LiquidBlood3", 90, -55, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile("XDeathHeadD3Maledict", 90, -55, random (10, 15), 2, random (80, 90));
		D3MJ P 6;
		D3MJ Q 6;
		D3MJ R 6;
		D3MJ S 6;
		TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 220, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("NashGoreBloodSpurt", 220, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_LiquidBlood3", 220, 0, random (0, 360), 2, random (0, 40));
		D3MJ T 8;
		D3MJ UV 7;
	FallNoHead2:
		D3MJ WXYZ 6;
	FallLoopNoHead:
		D3MJ Z 1 A_CheckFloor("SpawnCorpseNoHead");
	Loop;

	DeathNoHead1:
		TNT1 A 0;
		D3MJ WXYZ 6;
	DeathLoopNoHead1:
		D3MJ Z 1 A_CheckFloor("SpawnCorpseNoHead");
	Loop;

	DeathNoHead2:
		TNT1 A 0;
		D3MJ WXYZ 6;
	DeathLoopNoHead2:
		D3MJ Z 1 A_CheckFloor("SpawnCorpseNoHead");
	Loop;


	SpawnCorpseNoHead:
		TNT1 A 0;
		TNT1 A 0 A_StartSound("Corpse/Fall",CHAN_6);
		TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
		TNT1 A 0 A_SpawnItem("DeadD3MaledictNoHead");
	Stop;

	XDeath:
	Death.Explosiveimpact:
	Death.Explosives: 
	Death.Landmine:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
		TNT1 A 0 A_SpawnItem("BloodSplasher3");
		TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 30, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (70, 90));
		TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 100, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (20, 90));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (0, 160));
		TNT1 AAAAAAA 0 A_SpawnProjectile ("XDeath3", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (0, 160));
		TNT1 AAAAAAA 0 A_SpawnProjectile ("XDeath4", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath4b", 32, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("SuperGoreSpawner2", 10, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (0, 180));
		TNT1 AAAAAAAAAA 0 A_SpawnProjectile ("SuperGoreSpawner2", 0, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (0, 180));
		TNT1 AAAAA 0 A_SpawnProjectile ("SuperGoreSpawner2", 25, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (0, 180));
		TNT1 AAAAAAAAAA 0 A_SpawnProjectile ("SuperGoreSpawner2", 35, 0, random (0, 180), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("SuperGoreMist", 54, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_SAVEPITCH, -random (0, 90));
		TNT1 A 0 A_SpawnItem ("GiantBloodSpot");
		TNT1 A 0 A_SpawnProjectile ("XDeathHeadD3Maledict", 94, 0, random (0, 360), 2, random (0, 360));
		TNT1 AA 0 A_SpawnProjectile ("XDeathWingD3Maledict", 80, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_SpawnProjectile ("XDeathHumpD3Maledict", 80, 0, random (0, 360), 2, random (0, 360));
		TNT1 AA 0 A_SpawnProjectile ("XDeathFeetD3Maledict", 25, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_SpawnProjectile ("XDeathTailD3Maledict", 32, 0, random (0, 360), 2, random (0, 360));
	Stop;


	Death.Ice:
	Death.IceExplosion:
	Death.Freeze:
	Death.Frost:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
		TNT1 A 0 A_JumpIf (flight > 0, "FD2");
		TNT1 A 0 A_SpawnItem("FrozenD3Maledict");
	Stop;

	FD2:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("FrozenD3Maledict2");
	Stop;


	Death.Blackhole:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
		TNT1 A 0 A_SpawnItem("BlackHoledD3Maledict");
	Stop;


	Death.Shrink:
		TNT1 A 0;
		TNT1 A 0 A_KillChildren ("ShieldBreak", KILS_FOILINVUL, "D3HGPortalEffect");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 1 A_StartSound("Shrink", 3);
		TNT1 A 0 A_SpawnItemEx ("D3MaledictShrinkFX1", 0, 0,  5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("D3MaledictShrinkFX2", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("D3MaledictShrinkFX3", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("D3MaledictShrinkFX4", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("D3MaledictShrinkFX5", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("D3MaledictShrinkFX6", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("D3MaledictShrinkFX7", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("D3MaledictShrinkFX8", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("D3MaledictShrinkFX9", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("D3MaledictShrinkFX10", 0, 0, 5, 0, 0);
		TNT1 A 1 A_SpawnItemEx ("LilD3Maledict", 1);
		TNT1 A 0 A_PB_DropStormcastBossLoot;
	Stop;

	Death.Fire:
	Death.Burn:
	TNT1 A 0;
	TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death.Incinerate");
	TNT1 A 0 A_BossDeath;
	TNT1 A 0 {bSHOOTABLE = false; bSOLID = false;}
	TNT1 A 0
		{
		if (Flight == 0)
				{A_SpawnItemEx ("BurningD3Maledict1",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		if (Flight == 1)
				{A_SpawnItemEx ("BurningD3Maledict2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		if (Flight == 2)
				{A_SpawnItemEx ("BurningD3Maledict3",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);}
		}
	Stop;

	Death.Execution:
		TNT1 A 0 A_StopAllSounds;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("BPtoken",5);
		TNT1 A 0 A_PB_DropStormcastBossLoot;
		Stop;
	}
}


Class MaledictFlamethrowerMissile: FastProjectile
{
Default
{
  Radius 3;
  Height 3;
  Speed 30;
  Projectile;
  +GETOWNER;
  +NOBLOCKMAP;
  +NOTELEPORT;
  +DONTSPLASH;
  +MISSILE;
  +FORCEXYBILLBOARD;
  +THRUSPECIES;
  +THRUACTORS;
  Damage 3;
  -RIPPER;
  +NOBLOOD;
  +NOBLOODDECALS;
  +BLOODLESSIMPACT;
  -BLOODSPLATTER;
  RenderStyle "Add";
  DamageType "Fire";
  Scale 0.7;
  Alpha 1.0;
  Gravity 0;
}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 {bTHRUACTORS = 0;}
		FIR5 ABC 1 BRIGHT;
		FIR3 A 1 BRIGHT;
		EXPL A 0 A_SpawnProjectile ("SmallFireTrail", 6, 0, 0, 2, random (0, 10));
		FIR3 B 1 BRIGHT;
		TNT1 A 0 A_Explode(4, 80, 0);
		EXPL A 0 A_SpawnProjectile ("SmallFireTrail", 6, 0, 0, 2, random (0, 30));
		FIR3 D 1 BRIGHT;
		FIR3 E 1 BRIGHT;
		EXPL A 0 A_SpawnProjectile ("SmallFireTrail", 6, 0, 0, 2, random (0, 50));
		FIR3 F 1 BRIGHT;
		TNT1 A 0 A_Explode(4, 80, 0);
		EXPL A 0 A_SpawnProjectile ("SmallFireTrail", 6, 0, 0, 2, random (-10, 60));
		FIR3 G 1 BRIGHT;
		FIR3 H 1 BRIGHT;
		EXPL A 0 A_SpawnProjectile ("SmallFireTrail", 6, 0, 0, 2, random (-60, 80));
		FIR3 I 1 BRIGHT;
		TNT1 A 0 A_Explode(4, 80, 0);
		EXPL A 0 A_SpawnProjectile ("FlamethrowerFireParticles", 6, 0, 0, 2, random (10, 20));
		FIR3 JKL 1 BRIGHT;
		TNT1 A 0 A_Explode(4, 125, 0);
		EXPL A 0 A_SpawnProjectile ("FlamethrowerFireParticles", 6, 0, random (0, 360), 2, random (10, 90));
		TNT1 A 0 A_Playsound("Afrit/Hellfire");
		Stop;
	Death:
		TNT1 A 0 A_Explode(4, 50, 0);
		EXPL AA 0 A_SpawnProjectile ("FlamethrowerFireParticles", 6, 0, random (0, 360), 2, random (10, 90));
	Stop;
	}
}

Class Shul: Actor
{
float sc;
float scu;
Default
{
  +CLIENTSIDEONLY;
  -SOLID;
  +NOCLIP;
  +THRUACTORS;
  +NOGRAVITY;
  +DONTFALL;
  +NOTELEPORT;
  -PUSHABLE;
  +NODAMAGETHRUST;
  +NOTARGET;
  +NORADIUSDMG;
  +INVULNERABLE;
  +NOBLOOD;
  +NOBLOODDECALS;
  +SHOOTABLE;
  +NOICEDEATH;
  +DONTTHRUST;
  RenderStyle "Add";
  Alpha 0;
  +ROLLSPRITE;
  Scale 0.0;
}
  States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
		sc = self.Scale.Y;
		scu = sc+0.05;
		}
		TNT1 A 0 A_SetRoll(random(0, 359));
		TNT1 A 0 A_SetScale((Scale.Y)*1.3, Scale.Y);
		TNT1 AAAAAAAAAA 1 Bright Light("PortalLight_Red")
			{
			A_SetScale((Scale.Y+scu)*1.3, Scale.Y+scu);
			A_FadeIn(0.2);
			}
		TNT1 AAAAAAAAAA 1 Bright Light("PortalLight_Red")
			{A_SetScale((Scale.Y+scu)*1.3, Scale.Y+scu);
			A_FadeOut(0.16);
			}
	Stop;

	Death:
		TNT1 AA 1 Bright
			{A_SetScale((Scale.Y+(scu*5))*1.3, Scale.Y+(scu*5));
			A_FadeOut(0.5);
			}
	Stop;
	}
}
