Class DarkLord : PB_Monster
{
int BossState;
int RocketCount;
int NumShots;
int RageChance;
const Gaussdist = 2300;
Mixin SummonerFunctions;
Mixin MP_VolumetricLaserBeam;
Default
{
  Tag "Dark Lord";
  Health 20000;
  Speed 20;
  Radius 40;
  Height 110;
  Mass 500000;
  Damage 50;
  Species "DarkLord";
  Scale 1.0;
  Obituary "%o was decimated by the Dark Lord.";
  DamageFactor "BFG", 0.5;
  DamageFactor "Plasma", 0.75;
  DamageFactor "Disintegrate", 0.5;
  DamageFactor "GreenFire", 0.5;
  DamageFactor "SSG", 0.75;
  DamageFactor "Blast", 0.75;
  DamageFactor "Cut", .75;
  DamageFactor "Freeze", 0.25;
  DamageFactor "Ice", .25;
  DamageFactor "Frost", .25;
  DamageFactor "Explosive", 1.1;
  DamageFactor "HKFT", 0.05;
  DamageFactor "Decaptate", 5.0;
  DamageFactor "Avoid", 0.0;
  DamageFactor "killme", 0.0;
  DamageFactor "GibRemoving", 0.0;
  DamageFactor "TeleportRemover", 0.0;
  DamageFactor "CauseObjectsToSplash", 0.0;
  DamageFactor "Blackhole", 0.75;
  DamageFactor "ExtremePunches", 1.0;
  DamageFactor "Crush", 10.0;
  DamageFactor "Blood", 0.0;
  DamageFactor "BlueBlood", 0.0;
  DamageFactor "GreenBlood", 0.0;
  Painchance 10;
  PainChance "Taunt", 255;
  PainChance "Head", 30;
  PainChance "Siphon", 255;
  PainChance "Cut", 2;
  PainChance "Saw", 2;
  PainChance "Disintegrate", 5;
  +DONTRIP;
  -NORADIUSDMG;
  +QUICKTORETALIATE;
  +NOICEDeath;
  +DONTHARMSPECIES;
  +NOTARGET;
  +NOINFIGHTING;
  +THRUSPECIES;
  +MTHRUSPECIES;
  +BOSS;
  +BUDDHA;
  +NOFEAR;
  +THRUGHOST;
  //+FULLVOLDeath;
  //+FULLVOLACTIVE;
  -PUSHABLE;
  +NODAMAGETHRUST;
  +FLOORCLIP;
  SeeSound "DarkCyber/Sight";
  Activesound "DarkCyber/Active";
  PainSound "DarkCyber/Pain";
  DeathSound "DarkCyber/Death";
  BloodType "CyberDemon_Blood", "SawBlood", "SawBlood";
  DropItem "SlayerPower", 40;
  DropItem "Demonpickup2", 255;
  DropItem "Demonpickup2", 255;
  DropItem "Crucible", 60;
  Damagefactor "Crucible", 2.0;
  PainChance "GloryFire", 64;
  PainChance "BloodPunch", 255;
  WoundHealth 800;
}
	override void Tick()
	{
		Super.Tick();

		if(BossState == 1 && Self.Health < 10000 && !InStateSequence(self.curstate, self.ResolveState("FalseDeath1")) && !InStateSequence(self.curstate, self.ResolveState("StateTo2")))
			{SetState(FindState("FalseDeath1"));}
		else return;
	}

	Void DarkLordClearEffects()
	{
		A_KillChildren ("ShieldBreak", KILS_FOILINVUL, "DarkLordPortalEffect");
		A_KillChildren ("ShieldBreak", KILS_FOILINVUL, "DarkCardinalCometCharging");
		A_RemoveChildren(1,RMVF_EVERYTHING, "FloorStandingStormSpawner");
	}


  States
	{

	Wound:
		"####" "#" 1
		{
			if(GetCvar("be_ExecutionsON"))
			{
				if(countinv("FinisherToken")==0) //if it isnt healing already
				{								//will heal and give the token that indicates it's executable
					A_SpawnItemEx("BaronHighlight",0,0,0,0,0,0,0,SXF_SETMASTER|SXF_NOCHECKPOSITION); //to highlight if ON, and to remove the token after the monster heals
					A_GiveInventory("FinisherToken",1);	//token to allow melee attack to execute
				}
				
				if(GetCvar("be_MonsterStagger")==1) //will the monsters stagger at all?
				{
					DarkLordClearEffects();
					bNOGRAVITY = false;
					return ResolveState("Stagger");	//stays there for a few seconds
				}
				else
				{
					return ResolveState(null);
				}
			}
			return ResolveState(null);
		}
		Goto See;
	Stagger:
		MAUK G 0
		{
			if(getcvar("be_ExecutionHighlight")==1)
			{	return ResolveState("PrepareStaggerHighlight");}
			else
			{	return ResolveState("StagLooper");	}
		}
		Goto StagLooper;
	PrepareStaggerHighlight:
		CARD P 0;
		Goto StagLooper;

	StagLooper:
		"####" "#" 4
		{
			if(!countinv("FinisherToken"))
			{
				bNOGRAVITY = true;
				return ResolveState("See");
			}
			if(getcvar("be_NoisyStagger") && countinv("PainSoundToken"))
			{ 
				A_Pain(); 
				A_TakeInventory("PainSoundToken");
			}
			return ResolveState(null);
		}
		"####" "#" 0;
		Loop;


	Death.Crucible:
		TNT1 A 0 A_SpawnItemEx("GlorySawPinataMax",0,0,Height / 2,random(0,8),0,random(0,8),random(0,360));
	Goto Death;

	Death.GloryFire:
		TNT1 A 0 A_SpawnItemEx("FlamePinataSpawnHigh",0,0,Height / 2,random(0,8),0,random(0,8),random(0,360));
	Goto Death;

	Pain.GloryFire:
		TNT1 A 0;
		TNT1 A 0 A_Jump (192, "See");
		TNT1 A 0 A_SpawnItemEx("FlamePinataSpawnHigh",0,0,Height / 2,random(0,8),0,random(0,8),random(0,360));
	Goto See;

	Death.BloodPunch:
		TNT1 A 0 A_GiveToTarget("BloodPunchKilled",1);
		TNT1 A 0 A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0 A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0 A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0 A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0 A_SpawnItemEx("GlorySawPinataMax",0,0,Height / 2,random(0,8),0,random(0,8),random(0,360));
	Goto Death;

	Pain.BloodPunch:
		TNT1 A 0 A_GiveToTarget("BloodPunchKilled",1);
		TNT1 A 0 A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0 A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0 A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
		TNT1 A 0 A_SpawnItemEx("BloodpunchWave", 0, 0, Height / 2, 0, 0, 0, 0, SXF_CLIENTSIDE|SXF_TRANSFERPITCH);
	Goto Pain;

	FalseDeath1:
		TNT1 A 0;
		TNT1 A 0 { A_ScaleVelocity(0); bINVULNERABLE = true; bSOLID = false;}
		CBEP H 10;
		EXPL A 0 Radius_Quake (6, 100, 0, 22, 0);
		TNT1 A 0
		{
			if (GetCvar("pb_enemyexplosiondamage") == true)
			{
				A_Explode(250,250,XF_HURTSOURCE);
			}
		}
		TNT1 AAAAA 0 A_SpawnProjectile ("ExplosionSpawner", 90, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAA 0 A_SpawnProjectile ("PBExplosionparticles3", 74, 0, random (0, 360), 2, random (40, 90));
		TNT1 AAA 0 A_SpawnProjectile ("PBExplosionparticles4", 76, 0, random (0, 360), 2, random (40, 90));
		TNT1 AA 0 A_SpawnItemEx("ExplosionFlamesBig2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION);
		TNT1 A 0 A_SpawnProjectile ("DarkLordXDeath", 0, 0, random (0, 360), 2, random (0, 160));
		CBEP I 3 A_Scream();
		CBEP JKL 3;
		CBEP M 3;
		CBEP O 3;
		TNT1 A 0
			{
			BossState = 2;
			Health = 10000;
			Speed = 25;
			Mass = 1000;
			Height = 110;
			bFLOAT = true;
			bNOGRAVITY = true;
			bINVULNERABLE = false;
			bSOLID = true;
			bSHOOTABLE = true;
			bFLOORCLIP = false;
			bBUDDHA = false;
			A_SpawnItemEx("DarkCardinalFireSpawner", 0, 0, 10, 0, 0, 0, 0, SXF_SETMASTER|SXF_NOCHECKPOSITION);
			}
	Goto See;

	StateTo2:
		TNT1 A 0;
		TNT1 A 0
			{
			BossState = 2;
			Health = 10000;
			Speed = 30;
			Mass = 1000;
			Height = 92;
			bFLOAT = true;
			bNOGRAVITY = true;
			bINVULNERABLE = false;
			bSOLID = true;
			bFLOORCLIP = false;
			bBUDDHA = false;
			A_GiveInventory("SeeFirst");
			A_SpawnItemEx("DarkCardinalFireSpawner", 0, 0, 10, 0, 0, 0, 0, SXF_SETMASTER|SXF_NOCHECKPOSITION);
			}
	Goto CardinalSpawnLoop;


	Spawn:
	Idle:
		TNT1 A 0;
		TNT1 A 0 {BossState = 1;}
		CBEP D 5;
		TNT1 A 0 A_CheckCeiling("StateTo2");

	SpawnLoop:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(BossState == 2, "CardinalSpawnLoop");
		CBEP D 10 A_Look();
	Loop;

	CardinalSpawnLoop:
		CARD AB 3 A_Look();
	Loop;

	See:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(BossState == 2, "CardinalSee");
		TNT1 A 0 A_JumpIfInventory("SeeFirst", 1, "SeeContinue");
		TNT1 A 0 A_Jump (256, "SeeNeverSeen");
	SeeContinue:
		TNT1 A 0;

		TNT1 A 0 A_Jump (200, "Rush");
		CBEP A 3 A_StartSound("monster/anhoof",5);
		TNT1 A 0 A_JumpIfTargetInLOS("FloorStomp",0,JLOSF_DEADNOJUMP,95);
		CBEP A 3;
		CBEP AA 2 A_Chase();
		TNT1 A 0 A_JumpIfTargetInLOS("FloorStomp",0,JLOSF_DEADNOJUMP,95);
		CBEP BB 2 A_Chase();
		CBEP BBC 2 A_Chase();
		TNT1 A 0 A_JumpIfTargetInLOS("FloorStomp",0,JLOSF_DEADNOJUMP,95);
		CBEP C 2 A_Chase();
		CBEP C 2;
		CBEP C 2 A_StartSound("cyber/metal",6);
		TNT1 A 0;
		CBEP D 2 A_Chase();
		CBEP D 2 A_Chase();
		TNT1 A 0 A_JumpIfTargetInLOS("FloorStomp",0,JLOSF_DEADNOJUMP,95);
		TNT1 A 0 ;
		CBEP DD 2 A_Chase();

	Loop;

	BossPossession:
		"####" "#" 0 {bINVULNERABLE = true;}
		"####" "#" 3;
		"####" "#" 3 A_Pain();
		"####" "#" 35 ACS_NamedExecuteAlways("Pos - Flicker effect");
		TNT1 A 0 {bINVULNERABLE = false;}
	Goto See;

	Rush:
		TNT1 A 0 A_Hoof;
		CBEP A 2 A_Chase();
		TNT1 A 0 A_SpawnItemEx("DarkCyberGhostA",0,0,0,0,0,0,0,128);
		CBEP A 2 A_Chase();
		TNT1 A 0 A_SpawnItemEx("DarkCyberGhostA",0,0,0,0,0,0,0,128);
		CBEP A 2 A_Chase();
		TNT1 A 0 A_SpawnItemEx("DarkCyberGhostB",0,0,0,0,0,0,0,128);
		CBEP B 2 A_Chase();
		TNT1 A 0 A_SpawnItemEx("DarkCyberGhostB",0,0,0,0,0,0,0,128);
		CBEP C 2 A_Chase();
		TNT1 A 0 A_SpawnItemEx("DarkCyberGhostC",0,0,0,0,0,0,0,128);
		CBEP C 2 A_Chase();
		TNT1 A 0 A_Metal;
		TNT1 A 0 A_SpawnItemEx("DarkCyberGhostC",0,0,0,0,0,0,0,128);
		CBEP D 2 A_Chase();
		TNT1 A 0 A_SpawnItemEx("DarkCyberGhostD",0,0,0,0,0,0,0,128);
		CBEP D 2 A_Chase();
		TNT1 A 0 A_SpawnItemEx("DarkCyberGhostD",0,0,0,0,0,0,0,128);
		TNT1 A 0 A_Jump (64,"See");
	Loop;

	CardinalSee:
		TNT1 A 0;
		TNT1 A 0 DarkLordClearEffects();
		TNT1 A 0 A_ScaleVelocity(0);
		TNT1 A 0 {Speed = 30;}
	CardinalSeeRushContinue:
		TNT1 A 0;
		TNT1 A 0 A_Jump (100,"CardinalRush");
		CARD AB 3 A_Chase();
		TNT1 A 0 {RageChance++;}
	Loop;

	CardinalRush:
		TNT1 A 0;
		TNT1 A 0 {Speed = 40;}
	CardinalRushContinue:
		TNT1 A 0;
		CARD A 1 A_Chase();
		CARD B 1 A_SpawnItemEx("GenericRushGhost",0,0,0,0,0,0,0,SXF_TRANSFERSCALE|SXF_TRANSFERSPRITEFRAME);
		CARD A 1 A_Chase();
		CARD B 1 A_SpawnItemEx("GenericRushGhost",0,0,0,0,0,0,0,SXF_TRANSFERSCALE|SXF_TRANSFERSPRITEFRAME);
		CARD A 1 A_Chase();
		CARD B 1 A_SpawnItemEx("GenericRushGhost",0,0,0,0,0,0,0,SXF_TRANSFERSCALE|SXF_TRANSFERSPRITEFRAME);
		TNT1 A 0 A_Jump (100,"CardinalSee");
	Loop;

		
	Missile:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(BossState == 2, "CardinalMissile");
		TNT1 A 0 A_Jump (256,"Rockets", "Hellcomet", "Railgun", "BFG15K");
	Rockets:
		CBEP EEEEEE 5 A_FaceTarget();
		TNT1 A 0 {NumShots = random(3,7);}
	RocketsContinue:
		TNT1 A 0;

		TNT1 A 0 A_CheckSight("see");
		TNT1 A 0 A_JumpIfCloser(300, "FloorStomp");
		TNT1 A 0 A_SpawnProjectile("DarkCyberRocket",50,-21,0,0);
		TNT1 A 0 A_FaceTarget();
		CBEP F 8 Bright;
		TNT1 A 0 A_FaceTarget();
		CBEP E 10;
		TNT1 A 0 {NumShots = NumShots - 1;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "RocketsContinue");
	Goto See;

	Hellcomet:
		TNT1 A 0;
		TNT1 A 0 {NumShots = random(2,5);}
	HellCometContinue:
		TNT1 A 0;
		TNT1 A 0 A_CheckSight("see");
		TNT1 A 0 A_JumpIfCloser(300, "FloorStomp");
		TNT1 A 0 A_StartSound("DarkCyber/Cometcharge",2,1.0,0,0.6);
		TNT1 A 0 A_FaceTarget();
		CBEP E 5 {A_FaceTarget();}
		CBEP E 5 {A_FaceTarget(); A_SpawnItemEx("Hellcometcharge",0,-21,46,0,0,0,0);}
		CBEP E 5 {A_FaceTarget();}
		CBEP E 5 {A_FaceTarget(); A_SpawnItemEx("Hellcometcharge",0,-21,46,0,0,0,0);}
		CBEP E 5 {A_FaceTarget();}
		CBEP E 5 {A_FaceTarget(); A_SpawnItemEx("Hellcometcharge",0,-21,46,0,0,0,0);}
		CBEP F 5 Bright {A_FaceTarget(); A_SpawnProjectile("Hellcomet",50,-21,0,0);}
		TNT1 A 0 {NumShots = NumShots - 1;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "HellCometContinue");
		TNT1 A 0 A_FaceTarget();
		CBEP E 10;
	Goto See;

	FloorStomp:
		TNT1 A 0 A_FaceTarget();
		CBEP G 10;
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_SetInvulnerable;
		TNT1 A 0 A_SpawnItem("DarklordFlameSpawner",0,0,0,0);
		CBE3 G 3 Bright A_StartSound("DarkCyber/Laugh",5);
		TNT1 A 0 A_FaceTarget();
		CBE3 G 3 Bright A_SpawnItem("DarklordFlameSpawner",0,0,0,0);
		TNT1 A 0 A_FaceTarget();
		CBE3 G 3 Bright A_SpawnItem("DarklordFlameSpawner",0,0,0,0);
		TNT1 A 0 A_FaceTarget();
		CBE3 G 3 Bright A_SpawnItem("DarklordFlameSpawner",0,0,0,0);
		TNT1 A 0 A_FaceTarget();
		CBE3 G 3 Bright A_SpawnItem("DarklordFlameSpawner",0,0,0,0);
		TNT1 A 0 A_FaceTarget();
		CBE3 G 3 Bright A_SpawnItem("DarklordFlameSpawner",0,0,0,0);
		TNT1 A 0 A_UnsetInvulnerable;
		CBEP G 7 A_FaceTarget();
		CBE3 A 5 A_FaceTarget();
		TNT1 A 0 A_SpawnProjectile("CyberStomp",10,0,0,CMF_CHECKTARGETDEAD);
		TNT1 A 0 Radius_Quake(10,8,0,24,0);
		CBE3 B 6 A_StartSound("hellsmith/melee");
		CBE3 B 2 A_SpawnProjectile("DarklordFireSpawner",0,0,0,0);
		TNT1 A 0 A_SpawnProjectile("DarklordFireSpawner",0,0,15,0);
		CBE3 B 2 A_SpawnProjectile("DarklordFireSpawner",0,0,-15,0);
		TNT1 A 0 A_SpawnProjectile("DarklordFireSpawner",0,0,30,0);
		CBE3 B 2 A_SpawnProjectile("DarklordFireSpawner",0,0,-30,0);
		TNT1 A 0 A_SpawnProjectile("DarklordFireSpawner",0,0,45,0);
		CBE3 B 2 A_SpawnProjectile("DarklordFireSpawner",0,0,-45,0);
		CBE3 B 10;
		CBE3 B 10;
		TNT1 A 0 A_Jump (128,"Railgun","Hellcomet","BFG15K");
	Goto See;

	Railgun:
	    TNT1 A 0;
	    TNT1 A 0 {NumShots = random(1,3);}
	RailgunContinue:
	    TNT1 A 0;
	    TNT1 A 0 A_CheckSight("See");
	    TNT1 A 0 A_FaceTarget();
	    CBEP EEEE 5 Bright A_FaceTarget();
	    //CBEP E 10 Bright {A_FaceTarget(); A_SpawnItemEx("LaserChargeIndicator",0,-21,46,0,0,0,0);}
	    TNT1 A 0 A_StartSound("UNMCHG", 1, CHANF_OVERLAP);
		//TNT1 A 0 A_StartSound("UNMSTA", 2, CHANF_OVERLAP);
		CBEP EEEEE 2 Bright
				{
				A_FaceTarget();
				A_SpawnProjectile("FakeDarkLordActor",50,-22,0,CMF_OFFSETPITCH,0);
				A_SpawnItemEx("DarklordChargeIndicator",5,-21,46,0,0,0,0,SXF_NOCHECKPOSITION);
				}
	    TNT1 A 0 A_FaceTarget();
	    TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_JumpIf(TrDistance(self, target) > (Gaussdist - 100), "Rockets");
		CBEP EEEEE 2 Bright A_FaceTarget();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0
			{
				if (target)
				{
					laserAimPoint = target.pos + (0, 0, target.Height * 0.6);
				}
			}
		CBEP E 5 Bright;
		TNT1 A 0
			{
			A_StartSound("monsters/darkcyberrail", 0, CHANF_OVERLAP);
			A_CustomLaserAttack(50, -26, 5, 0, "DarklordRail", "DarklordRailPuff", "None", Gaussdist, Gaussdist, 12.0, 0.0, 15.0, 1, "Scorch", "Railgun", false, false, laserAimPoint);
			A_CustomLaserAttack(0, -26, -10, 0, "DarklordRailWave", "None", "None", Gaussdist, Gaussdist, 60.0, 0.0, 15.0, 1, "None", "Normal", false, false, laserAimPoint);
			}
		CBEP F 2 Bright;
	    TNT1 A 0 A_FaceTarget();
	    CBEP EEE 5 A_FaceTarget();
	    TNT1 A 0 {NumShots = NumShots - 1;}
	    TNT1 A 0 A_JumpIf(NumShots > 0, "RailgunContinue");
	Goto See;

	BFG15K:
		TNT1 A 0;
		TNT1 A 0 {RocketCount = random(1,3);}
	BFG15KStart:
		TNT1 A 0 {NumShots = 20;}
		TNT1 A 0 A_StartSound("DarkCyber/Infernalchrg", 0, CHANF_OVERLAP);
	BFG15KContinue:
		TNT1 A 0;
		TNT1 A 0 A_CheckSight("See");
		TNT1 A 0 A_FaceTarget();
		CBEP E 3 Bright {A_FaceTarget(); A_SpawnItemEx("InfernalChargeIndicator",5,-21,56,0,0,0,0,SXF_NOCHECKPOSITION);}
		TNT1 A 0 {NumShots --;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "BFG15KContinue");
	BFG15KShot:
		TNT1 A 0 A_FaceTarget();
		CBEP F 4 Bright A_SpawnProjectile("Infernalshot",50,-21,0,0);
		TNT1 A 0 {RocketCount --;}
		TNT1 A 0 A_JumpIf(RocketCount > 0, "BFG15KStart");
	Goto See;



	CardinalMissile:
		TNT1 A 0;
		TNT1 A 0 A_Jump (256, "CardinalRockets","CardinalSeekers","BigComet","BFG10K","HellLimbo");

	CardinalMissileNoGhosts:
		TNT1 A 0;
		TNT1 A 0 A_Jump (256, "CardinalRockets","CardinalSeekers","BigComet","BFG10K");
	CardinalRockets:
		CARD CCCC 5 Bright A_FaceTarget();
		TNT1 A 0 {NumShots = random(3,7);}
	CardinalRocketsContinue:
		TNT1 A 0 A_CheckSight("see");
		TNT1 A 0 A_FaceTarget();
		CARD D 8 Bright A_SpawnProjectile ("DarkCyberRocket",50,-21,0,0);
		TNT1 A 0 A_FaceTarget();
		CARD C 10 Bright;
		TNT1 A 0 {NumShots = NumShots - 1;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "CardinalRocketsContinue");
	Goto See;

	CardinalSeekers:
		TNT1 A 0 A_FaceTarget();
		CARD CCCC 5 Bright A_FaceTarget();
		TNT1 A 0 {NumShots = random(2,5);}
	CardinalSeekersContinue:
		TNT1 A 0 A_CheckSight("see");
		TNT1 A 0 A_FaceTarget();
		CARD D 8 Bright A_SpawnProjectile ("Darkcardinalseekermissile",50,-21,0,0);
		TNT1 A 0 A_FaceTarget();
		CARD C 8 Bright A_FaceTarget();
		TNT1 A 0 {NumShots = NumShots - 1;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "CardinalSeekersContinue");
		//TNT1 A 0 A_JumpIf(health <= 3000,"PainRage")
	Goto See;

	BigComet:
		TNT1 A 0;
		TNT1 A 0 {bNOPAIN = true;}
		TNT1 A 0 A_StartSound("Cardinal/Laugh",2,1.0,0,0.6);
		TNT1 A 0 A_SpawnItemEx("DarkCardinalCometCharging", 5, 50, 117, 0, 0, 0, 0, SXF_SETMASTER|SXF_NOCHECKPOSITION);
		TNT1 A 0 A_FaceTarget();
		CARD NM 5 A_FaceTarget();
		CARD MM 5 A_FaceTarget();
		TNT1 A 0 A_Jumpif (TrDistance(self, target) > 1000, "BigCometFInally");
		TNT1 A 0 {NumShots = random(8,15);}
	SmallCometsContinue:
		TNT1 A 0 A_CheckSight("CometEnd");
		TNT1 A 0 A_FaceTarget();
		CARD M 5 A_SpawnProjectile("DarkCardinalSmallComet",117, 50,random(-20,20),CMF_OFFSETPITCH,random(-10,5));
		TNT1 A 0 {NumShots = NumShots - 1;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "SmallCometsContinue");
	BigCometFInally:
		TNT1 A 0 A_CheckSight("CometEnd");
		TNT1 A 0 DarkLordClearEffects();
		TNT1 A 0 A_SpawnProjectile("DarkCardinalComet",117, 50);
		CARD NN 5 A_FaceTarget();
		CARD O 10;
		TNT1 A 0 A_FaceTarget();
		CARD O 10;
	CometEnd:
		TNT1 A 0 DarkLordClearEffects();
		TNT1 A 0 {bNOPAIN = false;}
	Goto See;

	BFG10K:
		TNT1 A 0;
		TNT1 A 0 {NumShots = random(2,5);}
	BFG10KContinue:
		TNT1 A 0 A_CheckSight("BFG10KEnd");
		TNT1 A 0 A_StartSound("weapons/rgcharge",2,1.0,0,0.6);
		TNT1 A 0 A_FaceTarget();
		CARD C 9 Bright;
		TNT1 A 0 A_FaceTarget();
		CARD C 9 Bright {A_FaceTarget(); A_SpawnItemEx("LaserChargeIndicator",0,-21,46,0,0,0,0);}
		TNT1 A 0 Bright A_StartSound("Cardinal/ElectroBall",2,1.0,0,0.6);
		TNT1 A 0 A_FaceTarget();
		CARD D 3 Bright A_SpawnProjectile("DarkCardinalShotHell",50,-21,0,0);
		TNT1 A 0 A_FaceTarget();
		CARD D 3 Bright;
		TNT1 A 0 {NumShots = NumShots - 1;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "BFG10KContinue");
	BFG10KEnd:
		TNT1 A 0 A_FaceTarget();
		CARD C 10 Bright;
		TNT1 A 0 A_FaceTarget();
		CARD C 10 Bright;
		//TNT1 A 0 A_JumpIf(health <= 3000,"PainRage")
	Goto See;

	HellLimbo:
		TNT1 A 0;
		TNT1 A 0 CountReinforcements("HellGhostMonster", GetCVar("HellGhostCount"), "CardinalMissileNoGhosts");
		TNT1 A 0 {bNOPAIN = true;}
		TNT1 A 0 A_StartSound("Cardinal/Laugh",2,1.0,0,0.6);
		TNT1 A 0 A_SpawnItemEx("DarkLordPortalEffect", 5, 50, 117, 0, 0, 0, 0, SXF_SETMASTER|SXF_NOCHECKPOSITION);
		TNT1 A 0 A_FaceTarget();
		CARD NNMM 5 A_FaceTarget();
		TNT1 A 0 {NumShots = random(3,5);}
	Ghosts:
		TNT1 A 0;
		TNT1 A 0 CountReinforcements("HellGhostMonster", GetCVar("HellGhostCount"), "HellLimboEnd");
		TNT1 A 0 A_CheckSight("HellLimboEnd");
		TNT1 A 0 A_FaceTarget();
		CARD M 5 SpawnReinforcement("HellGhostMonster",45, -50, 117, self, self, target, "SkullAttack", 0, 0, "DarkLord", 1, 0, 0);
		TNT1 A 0 {NumShots = NumShots - 1;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "Ghosts");
	HellLimboEnd:
		TNT1 A 0 DarkLordClearEffects();
		CARD MMNN 5 A_FaceTarget();
		TNT1 A 0 {bNOPAIN = false;}
	Goto See;



	Pain:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(BossState == 2, "CardinalPain");
		TNT1 A 0 A_Jump (200, "RocketRain");
		TNT1 A 0 A_Pain();
		CBEP GGGGG 2;
	Goto See;

	Pain.Taunt:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(BossState == 2, "CardinalPain");
		TNT1 A 0 A_Pain();
	SeeNeverSeen:
		TNT1 A 0;
		TNT1 A 0 {bNOPAIN = true;}
		TNT1 A 0 A_StartSound("Cardinal/Sight", 1);
		TNT1 A 0 Radius_Quake (6, 100, 0, 22, 0);
		CBE4 A 1 A_FaceTarget();
		CBE4 ABCCBADE 4;
		CBE4 FGHGFGHGFGHGFGHG 3;
		CBE4 EDA 4;
		TNT1 A 0 A_GiveInventory("SeeFirst", 1, 0);
		TNT1 A 0 {bNOPAIN = false;}
	Goto SeeContinue;

	RocketRain:
		TNT1 A 0 A_StartSound("Cardinal/Sight",2,1.0,0,0.6);
		CBEP G 10 A_Pain();
		TNT1 A 0 {bNOPAIN = true;}
		TNT1 A 0 A_JumpIfCloser(384,"RocketRainShort");
		TNT1 A 0 {RocketCount = random(10,15);}
	Goto RocketRainLoop;

	RocketRainLoop:
		TNT1 A 0 A_FaceTarget();
		CBEP G 5 A_SpawnItemEx("DarkLordRocketRainUpwards", 0,0,70, frandom(5.0,-5.0),frandom(5.0,-5.0),20, 0,SXF_NOCHECKPOSITION);
		TNT1 A 0 A_VileTarget("DarkLordGroundTarget");
		TNT1 A 0 {RocketCount = RocketCount - 1;}
		TNT1 A 0 A_JumpIf(RocketCount>=0,"RocketRainLoop");

	EndRocketRain:
		TNT1 A 0;
		TNT1 A 0 {RocketCount = 0;}
		TNT1 A 0 {bNOPAIN = false;}
		CBEP G 10;
		CBEP G 10;
		CBEP G 10;
		CBEP G 5;
	Goto See;

	RocketRainShort:
		TNT1 A 0 {RocketCount = random(3,5);}
	Goto RocketRainLoop;


	CardinalPain:
		TNT1 A 0;
		TNT1 A 0 DarkLordClearEffects();
		TNT1 A 0 A_JumpIf (RageChance > 5,"PainRage");
		TNT1 A 0 {RageChance++;}
		CARD E 3 Bright A_Pain();
		CARD E 3 Bright;
		CARD E 3 Bright;
	Goto See;

	PainRage:
		TNT1 A 0;
		TNT1 A 0 {RageChance = 0;}
		CARD E 3 Bright A_Pain();
		TNT1 A 0 A_JumpIfCloser(1000, 2);
		TNT1 A 0 A_Jump (256, "DistantHellStorm");
		CARD EEEE 3 Bright;
		TNT1 A 0 Bright A_SetInvulnerable;
		TNT1 A 0 Bright Radius_Quake(10,80,0,24,0);
		TNT1 A 0 Bright A_GiveInventory("Health",1000) ;
		TNT1 A 0 A_StartSound("Cardinal/Sight",2,1.0,0,0.6);
		TNT1 A 0 {NumShots = random(50,60);}
	LargeHellStormContinue:
		TNT1 A 0 Bright A_SpawnItemEx("Darkcardinalragecharge",0,0,80,0,0,0,0,SXF_NOCHECKPOSITION);
		CARD E 2 Bright A_SpawnItemEx("FloorStandingStormSpawner",Random(1000,-1000),Random(1000,-1000),0,0,0,0,0,SXF_NOCHECKPOSITION | SXF_SETMASTER);
		TNT1 A 0 {NumShots = NumShots - 1;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "LargeHellStormContinue");
	Shield:
		TNT1 A 0 A_SpawnProjectile("RainCometAttack",50,0);
		TNT1 A 0 {NumShots = random(40,50);}
	ShieldContinue:
		TNT1 A 0 Bright  A_SpawnItemEx("Darkcardinalragecharge",0,0,80,0,0,0,0,SXF_NOCHECKPOSITION);
		CARD E 2 Bright;
		TNT1 A 0 {NumShots = NumShots - 1;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "ShieldContinue");
		CARD E 10 DarkLordClearEffects();
		TNT1 A 0 Bright A_UnSetInvulnerable;
		CARD EE 3 Bright;
	Goto See;

	DistantHellStorm:
		TNT1 A 0;
		CARD EEEE 3 Bright;
		TNT1 A 0 Bright A_SetInvulnerable;
		TNT1 A 0 Bright Radius_Quake(10,80,0,24,0);
		TNT1 A 0 Bright A_GiveInventory("Health",1000) ;
		TNT1 A 0 A_StartSound("Cardinal/Sight",2,1.0,0,0.6);
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_SpawnProjectile("RainCometAttack",50,0);
	Shield2:
		TNT1 A 0 {NumShots = 60;}
	Shield2Continue:
		TNT1 A 0 Bright  A_SpawnItemEx("Darkcardinalragecharge",0,0,80,0,0,0,0,SXF_NOCHECKPOSITION);
		CARD E 2 Bright;
		TNT1 A 0 {NumShots = NumShots - 1;}
		TNT1 A 0 A_JumpIf(NumShots > 0, "Shield2Continue");
		CARD E 10 DarkLordClearEffects();
		TNT1 A 0 Bright A_UnSetInvulnerable;
		CARD EE 3 Bright;
	Goto See;



	Pain.Siphon:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(BossState == 2, "CardinalPainSiphon");
		TNT1 AAA 0 A_SpawnItemEx ("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
		CBEP G 1
		{
		A_FaceTarget();
		A_GiveToTarget("HealthBonus",4);
		}
		CBEP G 5 A_FaceTarget();
		TNT1 A 0 A_Pain();
	Goto See;


	CardinalPainSiphon:
		TNT1 A 0;
		TNT1 AAA 0 A_SpawnItemEx ("RedLightning_Small", random (-12, 12), random (-12, 12), random (16, 52), 0, 0);
		CARD E 1
		{
		A_FaceTarget();
		A_GiveToTarget("HealthBonus",4);
		}
		CARD E 5 A_FaceTarget();
		TNT1 A 0 A_Pain();
	Goto See;


	Death:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		CARD E 10 {A_Scream(); DarkLordClearEffects(); A_RemoveChildren(1,RMVF_EVERYTHING, "DarkCardinalFireSpawner");}
		CARD F 10;
		EXPL A 0 Radius_Quake (6, 100, 0, 22, 0);
		TNT1 A 0
		{
			if (GetCvar("pb_enemyexplosiondamage") == true)
			{
				A_Explode(250,250,XF_HURTSOURCE);
			}
		}
		TNT1 AAAAA 0 A_SpawnProjectile ("ExplosionSpawner", 90, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAA 0 A_SpawnProjectile ("PBExplosionparticles3", 74, 0, random (0, 360), 2, random (40, 90));
		TNT1 AAA 0 A_SpawnProjectile ("PBExplosionparticles4", 76, 0, random (0, 360), 2, random (40, 90));
		TNT1 AA 0 A_SpawnItemEx("ExplosionFlamesBig2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION);
		TNT1 A 0 A_SpawnProjectile ("DarkCardinalXDeath", 0, 0, random (0, 360), 2, random (0, 160));
		CARD G 5;
		CARD HIJ 5;
		CARD K 5;
		TNT1 A 0 A_BossDeath();
		CARD L 5;
	Stop;

	Death.Head:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_JumpIfInTargetInventory("HasIncendiaryWeapon",1,"Death");
		TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death");
		TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.decaptate");
		TNT1 A 0 {A_Scream(); DarkLordClearEffects(); A_RemoveChildren(1,RMVF_EVERYTHING, "DarkCardinalFireSpawner");}
		TNT1 A 0 A_SpawnItemEx("BeheadedDarkCardinal", 0, 0, 0, SXF_NOCHECKPOSITION);
		TNT1 A 0 A_SpawnItemEx("CardinalHeadExplode", 105, 0, 0, SXF_NOCHECKPOSITION);
	Stop;

	Death.Decaptate:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_BossDeath();
		TNT1 A 0 A_SpawnProjectile ("XDeathDarkLordHead", 105, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 {A_Scream(); DarkLordClearEffects(); A_RemoveChildren(1,RMVF_EVERYTHING, "DarkCardinalFireSpawner");}
		TNT1 A 0 A_SpawnItemEx("BeheadedDarkCardinal", 0, 0, 0, SXF_NOCHECKPOSITION);
	Stop;

	Death.Execution:
		TNT1 A 0 {
		A_StopSound();
		A_FaceTarget();
		A_NoBlocking();
		A_BossDeath();
		A_Scream();
		DarkLordClearEffects(); A_RemoveChildren(1,RMVF_EVERYTHING, "DarkCardinalFireSpawner");
		}
		TNT1 A 0 A_GiveToTarget("BPtoken",5);
		Stop;
		}
 }



Class DarkCardinalFireSpawner: Actor
{
int fx;
Default
{
  Scale 0.0;
  Projectile;
  +CLIENTSIDEONLY;
  -SOLID;
  +NOGRAVITY;
  +DONTFALL;
  +FORCEXYBILLBOARD;
  +NOINTERACTION;
}

	override void Tick()
	{
		Super.Tick();
		if (!master || master.health < 1)
		{
			SetState(FindState("Death"));
			return;
		}
		A_Warp(AAPTR_MASTER, 0, 0, 0, 0, WARPF_NOCHECKPOSITION);
	}


  States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 1
		{
		if(random(0,1) == 0) { A_SpawnItemEx("DarkCardialFirespawn2",random(2,26),0,random(45,55),frandom(-2,0),0,frandom(-8,0),random(0,360)); }
		else  { A_SpawnItemEx("DarkCardialFirespawn1",random(2,26),0,random(45,55),frandom(-2,0),0,frandom(-8,0),random(0,360)); }
		for(fx = 0;fx<=2;fx++) { A_SpawnItemEx("CardinalGroundFire",frandom(-20,20),frandom(-20,20),-1000,0,0,0,0,0,192); }
		}
	Loop;

	Death:
		TNT1 A 0;
	Stop;
		}
}

Class DarkLordGroundTarget : Actor
{
  int NumIteration;
Default
{
  Radius 1;
  Height 1;
  Scale 0;
  Alpha 0;
  Renderstyle "Add";
  Mass 50;
  +CLIENTSIDEONLY;
  -SOLID;
  +NOCLIP;
  +THRUACTORS;
  -NOGRAVITY;
  -DONTFALL;
  +NOTELEPORT;
  -PUSHABLE;
  +NODAMAGETHRUST;
  +NOTARGET;
  +NORADIUSDMG;
  +INVULNERABLE;
  +NOBLOOD;
  +NOBLOODDECALS;
  +SHOOTABLE;
  +NOICEDEATH;
  +DONTTHRUST;
  +FLATSPRITE;
  +FLOORHUGGER;
  +FLOORCLIP;
 }
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_ScaleVelocity(0);
		TNT1 A 0 A_SpawnItemEx("D16CyberdemonGroundTargetRay", 0, 0, 0, 0, 0, 0, 0, SXF_SETMASTER|SXF_NOCHECKPOSITION);
	SpawnLoop:
		TNT1 A 2 A_CheckFloor("SpawnContinue");
	Loop;
	SpawnContinue:
		VINR AAAAA 1 Bright {
			A_SetScale((Scale.Y+0.6), Scale.Y+0.6);
			A_FadeIn(0.2);
			}
		VINR A 35 Bright;
		TNT1 A 0 A_SpawnItemEx("D16CyberdemonocketRainDown", 0, 0, (ceilingz - floorz - 10), 0, 0, 0, 0, SXF_SETMASTER|SXF_NOCHECKPOSITION);

	Death:
	Death.KillEffects:
		TNT1 A 0;
		TNT1 A 0 A_KillChildren ("KillEffects", KILS_FOILINVUL, "D16CyberdemonGroundTargetRay");
		VINR AAAAA 1 {
			A_SetScale((Scale.Y-0.6), Scale.Y-0.6);
			A_FadeOut(0.2);
			}
	Stop;
	}
}