// GLDEFS.CyberdemonRL — brightmap sprite bindings (ported from PBX-Weapons brightmaps/CyberdemonRL.txt).

brightmap sprite CYBFA0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFA0.png" disablefullbright }
brightmap sprite CYBFB0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFB0.png" disablefullbright }
brightmap sprite CYBFC0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFC0.png" disablefullbright }
brightmap sprite CYBFD0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFD0.png" disablefullbright }
brightmap sprite CYBFE0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFE0.png" disablefullbright }
brightmap sprite CYBFF0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFF0.png" disablefullbright }
brightmap sprite CYBFG0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFG0.png" disablefullbright }
brightmap sprite CYBFH0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFH0.png" disablefullbright }
brightmap sprite CYBFI0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFI0.png" disablefullbright }
brightmap sprite CYBFJ0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFJ0.png" disablefullbright }
brightmap sprite CYBFK0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFK0.png" disablefullbright }
brightmap sprite CYBFL0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFL0.png" disablefullbright }
brightmap sprite CYBFM0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFM0.png" disablefullbright }
brightmap sprite CYBFN0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFN0.png" disablefullbright }
brightmap sprite CYBFO0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFO0.png" disablefullbright }
brightmap sprite CYBFP0 { map "brightmaps/WEAPONS/Slot6/CyberdemonRL/CYBFP0.png" disablefullbright }
