hardwareshader sprite D3MKA1 	{ Shader "shaders/glorykill.shader" Speed 1.0 }
hardwareshader sprite D3MKA2A8 	{ Shader "shaders/glorykill.shader" Speed 1.0 }
hardwareshader sprite D3MKA3A7 	{ Shader "shaders/glorykill.shader" Speed 1.0 }
hardwareshader sprite D3MKA4A6 	{ Shader "shaders/glorykill.shader" Speed 1.0 }
hardwareshader sprite D3MKA5 	{ Shader "shaders/glorykill.shader" Speed 1.0 }

flickerlight2 PortalLight_Red
{
	color 1.0 0.0 0.0
	size 90
	secondarySize 82
	interval 0.05
	offset 0 0 0
}
