hardwareshader sprite 0ORFT0     { Shader "shaders/glorykill.shader" Speed 1.0 }

Pulselight ObsidianGlow
{
	color 0.4 0.0 0.0
	size 16
	secondarySize 20
	interval 2.0
	offset 0 64 0
}

Pulselight ObsidianProjectileGlowLarge
{
	color 1.0 0.0 0.0
	size 16
	secondarySize 18
	interval 2.0
	offset 0 0 0
}
Pulselight ObsidianProjectileGlowSmall
{
	color 1.0 0.0 0.0
	size 10
	secondarySize 12
	interval 2.0
	offset 0 0 0
}

object ObsidianRavager
{
    frame VSTL { light ObsidianGlow }
}

object ChaosBall
{
    frame BAL7 { light ObsidianProjectileGlowLarge }
}
object ChaosBarrage
{
    frame BAL7 { light ObsidianProjectileGlowSmall }
}

BrightMap Sprite VSTLA1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLA1.png"
	DisableFullBright
}

BrightMap Sprite VSTLA2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLA2.png"
	DisableFullBright
}

BrightMap Sprite VSTLA3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLA3.png"
	DisableFullBright
}

BrightMap Sprite VSTLA4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLA4.png"
	DisableFullBright
}

BrightMap Sprite VSTLA5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLA5.png"
	DisableFullBright
}

BrightMap Sprite VSTLA6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLA6.png"
	DisableFullBright
}

BrightMap Sprite VSTLA7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLA7.png"
	DisableFullBright
}

BrightMap Sprite VSTLA8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLA8.png"
	DisableFullBright
}

BrightMap Sprite VSTLB1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLB1.png"
	DisableFullBright
}

BrightMap Sprite VSTLB2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLB2.png"
	DisableFullBright
}

BrightMap Sprite VSTLB3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLB3.png"
	DisableFullBright
}

BrightMap Sprite VSTLB4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLB4.png"
	DisableFullBright
}

BrightMap Sprite VSTLB5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLB5.png"
	DisableFullBright
}

BrightMap Sprite VSTLB6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLB6.png"
	DisableFullBright
}

BrightMap Sprite VSTLB7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLB7.png"
	DisableFullBright
}

BrightMap Sprite VSTLB8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLB8.png"
	DisableFullBright
}

BrightMap Sprite VSTLC1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLC1.png"
	DisableFullBright
}

BrightMap Sprite VSTLC2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLC2.png"
	DisableFullBright
}

BrightMap Sprite VSTLC3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLC3.png"
	DisableFullBright
}

BrightMap Sprite VSTLC4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLC4.png"
	DisableFullBright
}

BrightMap Sprite VSTLC5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLC5.png"
	DisableFullBright
}

BrightMap Sprite VSTLC6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLC6.png"
	DisableFullBright
}

BrightMap Sprite VSTLC7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLC7.png"
	DisableFullBright
}

BrightMap Sprite VSTLC8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLC8.png"
	DisableFullBright
}

BrightMap Sprite VSTLD1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLD1.png"
	DisableFullBright
}

BrightMap Sprite VSTLD2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLD2.png"
	DisableFullBright
}

BrightMap Sprite VSTLD3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLD3.png"
	DisableFullBright
}

BrightMap Sprite VSTLD4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLD4.png"
	DisableFullBright
}

BrightMap Sprite VSTLD5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLD5.png"
	DisableFullBright
}

BrightMap Sprite VSTLD6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLD6.png"
	DisableFullBright
}

BrightMap Sprite VSTLD7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLD7.png"
	DisableFullBright
}

BrightMap Sprite VSTLD8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLD8.png"
	DisableFullBright
}

BrightMap Sprite VSTLE1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLE1.png"
	DisableFullBright
}

BrightMap Sprite VSTLE2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLE2.png"
	DisableFullBright
}

BrightMap Sprite VSTLE3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLE3.png"
	DisableFullBright
}

BrightMap Sprite VSTLE4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLE4.png"
	DisableFullBright
}

BrightMap Sprite VSTLE5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLE5.png"
	DisableFullBright
}

BrightMap Sprite VSTLE6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLE6.png"
	DisableFullBright
}

BrightMap Sprite VSTLE7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLE7.png"
	DisableFullBright
}

BrightMap Sprite VSTLE8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLE8.png"
	DisableFullBright
}

BrightMap Sprite VSTLF1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLF1.png"
	DisableFullBright
}

BrightMap Sprite VSTLF2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLF2.png"
	DisableFullBright
}

BrightMap Sprite VSTLF3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLF3.png"
	DisableFullBright
}

BrightMap Sprite VSTLF4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLF4.png"
	DisableFullBright
}

BrightMap Sprite VSTLF5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLF5.png"
	DisableFullBright
}

BrightMap Sprite VSTLF6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLF6.png"
	DisableFullBright
}

BrightMap Sprite VSTLF7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLF7.png"
	DisableFullBright
}

BrightMap Sprite VSTLF8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLF8.png"
	DisableFullBright
}

BrightMap Sprite VSTLG1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLG1.png"
	DisableFullBright
}

BrightMap Sprite VSTLG2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLG2.png"
	DisableFullBright
}

BrightMap Sprite VSTLG3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLG3.png"
	DisableFullBright
}

BrightMap Sprite VSTLG4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLG4.png"
	DisableFullBright
}

BrightMap Sprite VSTLG5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLG5.png"
	DisableFullBright
}

BrightMap Sprite VSTLG6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLG6.png"
	DisableFullBright
}

BrightMap Sprite VSTLG7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLG7.png"
	DisableFullBright
}

BrightMap Sprite VSTLG8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLG8.png"
	DisableFullBright
}

BrightMap Sprite VSTLH1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLH1.png"
	DisableFullBright
}

BrightMap Sprite VSTLH2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLH2.png"
	DisableFullBright
}

BrightMap Sprite VSTLH3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLH3.png"
	DisableFullBright
}

BrightMap Sprite VSTLH4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLH4.png"
	DisableFullBright
}

BrightMap Sprite VSTLH5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLH5.png"
	DisableFullBright
}

BrightMap Sprite VSTLH6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLH6.png"
	DisableFullBright
}

BrightMap Sprite VSTLH7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLH7.png"
	DisableFullBright
}

BrightMap Sprite VSTLH8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLH8.png"
	DisableFullBright
}

BrightMap Sprite VSTLI1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLI1.png"
	DisableFullBright
}

BrightMap Sprite VSTLI2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLI2.png"
	DisableFullBright
}

BrightMap Sprite VSTLI3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLI3.png"
	DisableFullBright
}

BrightMap Sprite VSTLI4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLI4.png"
	DisableFullBright
}

BrightMap Sprite VSTLI5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLI5.png"
	DisableFullBright
}

BrightMap Sprite VSTLI6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLI6.png"
	DisableFullBright
}

BrightMap Sprite VSTLI7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLI7.png"
	DisableFullBright
}

BrightMap Sprite VSTLI8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLI8.png"
	DisableFullBright
}

BrightMap Sprite VSTLJ1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLJ1.png"
	DisableFullBright
}

BrightMap Sprite VSTLJ2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLJ2.png"
	DisableFullBright
}

BrightMap Sprite VSTLJ3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLJ3.png"
	DisableFullBright
}

BrightMap Sprite VSTLJ4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLJ4.png"
	DisableFullBright
}

BrightMap Sprite VSTLJ5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLJ5.png"
	DisableFullBright
}

BrightMap Sprite VSTLJ6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLJ6.png"
	DisableFullBright
}

BrightMap Sprite VSTLJ7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLJ7.png"
	DisableFullBright
}

BrightMap Sprite VSTLJ8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLJ8.png"
	DisableFullBright
}

BrightMap Sprite VSTLK1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLK1.png"
	DisableFullBright
}

BrightMap Sprite VSTLK2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLK2.png"
	DisableFullBright
}

BrightMap Sprite VSTLK3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLK3.png"
	DisableFullBright
}

BrightMap Sprite VSTLK4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLK4.png"
	DisableFullBright
}

BrightMap Sprite VSTLK5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLK5.png"
	DisableFullBright
}

BrightMap Sprite VSTLK6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLK6.png"
	DisableFullBright
}

BrightMap Sprite VSTLK7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLK7.png"
	DisableFullBright
}

BrightMap Sprite VSTLK8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLK8.png"
	DisableFullBright
}

BrightMap Sprite VSTLL1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLL1.png"
	DisableFullBright
}

BrightMap Sprite VSTLL2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLL2.png"
	DisableFullBright
}

BrightMap Sprite VSTLL3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLL3.png"
	DisableFullBright
}

BrightMap Sprite VSTLL4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLL4.png"
	DisableFullBright
}

BrightMap Sprite VSTLL5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLL5.png"
	DisableFullBright
}

BrightMap Sprite VSTLL6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLL6.png"
	DisableFullBright
}

BrightMap Sprite VSTLL7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLL7.png"
	DisableFullBright
}

BrightMap Sprite VSTLL8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLL8.png"
	DisableFullBright
}

BrightMap Sprite VSTLM1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLM1.png"
	DisableFullBright
}

BrightMap Sprite VSTLM2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLM2.png"
	DisableFullBright
}

BrightMap Sprite VSTLM3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLM3.png"
	DisableFullBright
}

BrightMap Sprite VSTLM4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLM4.png"
	DisableFullBright
}

BrightMap Sprite VSTLM5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLM5.png"
	DisableFullBright
}

BrightMap Sprite VSTLM6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLM6.png"
	DisableFullBright
}

BrightMap Sprite VSTLM7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLM7.png"
	DisableFullBright
}

BrightMap Sprite VSTLM8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLM8.png"
	DisableFullBright
}

BrightMap Sprite VSTLN1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLN1.png"
	DisableFullBright
}

BrightMap Sprite VSTLN2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLN2.png"
	DisableFullBright
}

BrightMap Sprite VSTLN3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLN3.png"
	DisableFullBright
}

BrightMap Sprite VSTLN4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLN4.png"
	DisableFullBright
}

BrightMap Sprite VSTLN5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLN5.png"
	DisableFullBright
}

BrightMap Sprite VSTLN6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLN6.png"
	DisableFullBright
}

BrightMap Sprite VSTLN7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLN7.png"
	DisableFullBright
}

BrightMap Sprite VSTLN8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLN8.png"
	DisableFullBright
}

BrightMap Sprite VSTLO1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLO1.png"
	DisableFullBright
}

BrightMap Sprite VSTLO2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLO2.png"
	DisableFullBright
}

BrightMap Sprite VSTLO3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLO3.png"
	DisableFullBright
}

BrightMap Sprite VSTLO4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLO4.png"
	DisableFullBright
}

BrightMap Sprite VSTLO5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLO5.png"
	DisableFullBright
}

BrightMap Sprite VSTLO6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLO6.png"
	DisableFullBright
}

BrightMap Sprite VSTLO7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLO7.png"
	DisableFullBright
}

BrightMap Sprite VSTLO8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLO8.png"
	DisableFullBright
}

BrightMap Sprite VSTLP1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLP1.png"
	DisableFullBright
}

BrightMap Sprite VSTLP2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLP2.png"
	DisableFullBright
}

BrightMap Sprite VSTLP3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLP3.png"
	DisableFullBright
}

BrightMap Sprite VSTLP4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLP4.png"
	DisableFullBright
}

BrightMap Sprite VSTLP5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLP5.png"
	DisableFullBright
}

BrightMap Sprite VSTLP6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLP6.png"
	DisableFullBright
}

BrightMap Sprite VSTLP7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLP7.png"
	DisableFullBright
}

BrightMap Sprite VSTLP8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLP8.png"
	DisableFullBright
}

BrightMap Sprite VSTLQ1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLQ1.png"
	DisableFullBright
}

BrightMap Sprite VSTLQ2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLQ2.png"
	DisableFullBright
}

BrightMap Sprite VSTLQ3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLQ3.png"
	DisableFullBright
}

BrightMap Sprite VSTLQ4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLQ4.png"
	DisableFullBright
}

BrightMap Sprite VSTLQ5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLQ5.png"
	DisableFullBright
}

BrightMap Sprite VSTLQ6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLQ6.png"
	DisableFullBright
}

BrightMap Sprite VSTLQ7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLQ7.png"
	DisableFullBright
}

BrightMap Sprite VSTLQ8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLQ8.png"
	DisableFullBright
}

BrightMap Sprite VSTLR1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLR1.png"
	DisableFullBright
}

BrightMap Sprite VSTLR2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLR2.png"
	DisableFullBright
}

BrightMap Sprite VSTLR3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLR3.png"
	DisableFullBright
}

BrightMap Sprite VSTLR4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLR4.png"
	DisableFullBright
}

BrightMap Sprite VSTLR5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLR5.png"
	DisableFullBright
}

BrightMap Sprite VSTLR6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLR6.png"
	DisableFullBright
}

BrightMap Sprite VSTLR7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLR7.png"
	DisableFullBright
}

BrightMap Sprite VSTLR8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLR8.png"
	DisableFullBright
}

BrightMap Sprite VSTLS1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLS1.png"
	DisableFullBright
}

BrightMap Sprite VSTLS2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLS2.png"
	DisableFullBright
}

BrightMap Sprite VSTLS3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLS3.png"
	DisableFullBright
}

BrightMap Sprite VSTLS4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLS4.png"
	DisableFullBright
}

BrightMap Sprite VSTLS5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLS5.png"
	DisableFullBright
}

BrightMap Sprite VSTLS6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLS6.png"
	DisableFullBright
}

BrightMap Sprite VSTLS7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLS7.png"
	DisableFullBright
}

BrightMap Sprite VSTLS8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLS8.png"
	DisableFullBright
}

BrightMap Sprite VSTLT1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLT1.png"
	DisableFullBright
}

BrightMap Sprite VSTLT2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLT2.png"
	DisableFullBright
}

BrightMap Sprite VSTLT3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLT3.png"
	DisableFullBright
}

BrightMap Sprite VSTLT4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLT4.png"
	DisableFullBright
}

BrightMap Sprite VSTLT5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLT5.png"
	DisableFullBright
}

BrightMap Sprite VSTLT6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLT6.png"
	DisableFullBright
}

BrightMap Sprite VSTLT7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLT7.png"
	DisableFullBright
}

BrightMap Sprite VSTLT8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLT8.png"
	DisableFullBright
}

BrightMap Sprite VSTLU1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLU1.png"
	DisableFullBright
}

BrightMap Sprite VSTLU2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLU2.png"
	DisableFullBright
}

BrightMap Sprite VSTLU3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLU3.png"
	DisableFullBright
}

BrightMap Sprite VSTLU4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLU4.png"
	DisableFullBright
}

BrightMap Sprite VSTLU5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLU5.png"
	DisableFullBright
}

BrightMap Sprite VSTLU6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLU6.png"
	DisableFullBright
}

BrightMap Sprite VSTLU7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLU7.png"
	DisableFullBright
}

BrightMap Sprite VSTLU8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLU8.png"
	DisableFullBright
}

BrightMap Sprite VSTLV1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLV1.png"
	DisableFullBright
}

BrightMap Sprite VSTLV2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLV2.png"
	DisableFullBright
}

BrightMap Sprite VSTLV3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLV3.png"
	DisableFullBright
}

BrightMap Sprite VSTLV4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLV4.png"
	DisableFullBright
}

BrightMap Sprite VSTLV5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLV5.png"
	DisableFullBright
}

BrightMap Sprite VSTLV6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLV6.png"
	DisableFullBright
}

BrightMap Sprite VSTLV7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLV7.png"
	DisableFullBright
}

BrightMap Sprite VSTLV8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLV8.png"
	DisableFullBright
}

BrightMap Sprite VSTLW1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLW1.png"
	DisableFullBright
}

BrightMap Sprite VSTLW2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLW2.png"
	DisableFullBright
}

BrightMap Sprite VSTLW3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLW3.png"
	DisableFullBright
}

BrightMap Sprite VSTLW4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLW4.png"
	DisableFullBright
}

BrightMap Sprite VSTLW5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLW5.png"
	DisableFullBright
}

BrightMap Sprite VSTLW6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLW6.png"
	DisableFullBright
}

BrightMap Sprite VSTLW7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLW7.png"
	DisableFullBright
}

BrightMap Sprite VSTLW8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLW8.png"
	DisableFullBright
}

BrightMap Sprite VSTLX1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLX1.png"
	DisableFullBright
}

BrightMap Sprite VSTLX2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLX2.png"
	DisableFullBright
}

BrightMap Sprite VSTLX3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLX3.png"
	DisableFullBright
}

BrightMap Sprite VSTLX4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLX4.png"
	DisableFullBright
}

BrightMap Sprite VSTLX5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLX5.png"
	DisableFullBright
}

BrightMap Sprite VSTLX6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLX6.png"
	DisableFullBright
}

BrightMap Sprite VSTLX7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLX7.png"
	DisableFullBright
}

BrightMap Sprite VSTLX8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLX8.png"
	DisableFullBright
}

BrightMap Sprite VSTLY1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLY1.png"
	DisableFullBright
}

BrightMap Sprite VSTLY2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLY2.png"
	DisableFullBright
}

BrightMap Sprite VSTLY3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLY3.png"
	DisableFullBright
}

BrightMap Sprite VSTLY4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLY4.png"
	DisableFullBright
}

BrightMap Sprite VSTLY5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLY5.png"
	DisableFullBright
}

BrightMap Sprite VSTLY6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLY6.png"
	DisableFullBright
}

BrightMap Sprite VSTLY7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLY7.png"
	DisableFullBright
}

BrightMap Sprite VSTLY8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLY8.png"
	DisableFullBright
}

BrightMap Sprite VSTLZ1
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLZ1.png"
	DisableFullBright
}

BrightMap Sprite VSTLZ2
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLZ2.png"
	DisableFullBright
}

BrightMap Sprite VSTLZ3
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLZ3.png"
	DisableFullBright
}

BrightMap Sprite VSTLZ4
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLZ4.png"
	DisableFullBright
}

BrightMap Sprite VSTLZ5
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLZ5.png"
	DisableFullBright
}

BrightMap Sprite VSTLZ6
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLZ6.png"
	DisableFullBright
}

BrightMap Sprite VSTLZ7
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLZ7.png"
	DisableFullBright
}

BrightMap Sprite VSTLZ8
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTLZ8.png"
	DisableFullBright
}

BrightMap Sprite VSTKA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTKA0.png"
	DisableFullBright
}

BrightMap Sprite VSTKB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTKB0.png"
	DisableFullBright
}

BrightMap Sprite VSTKC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTKC0.png"
	DisableFullBright
}

BrightMap Sprite VSTKD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTKD0.png"
	DisableFullBright
}

BrightMap Sprite VSTKE0
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTKE0.png"
	DisableFullBright
}

BrightMap Sprite VSTKF0
{
	Map "brightmaps/monsters/ObsidianRavager/BMVSTKF0.png"
	DisableFullBright
}

BrightMap Sprite 0ORFQ0
{
	Map "brightmaps/monsters/ObsidianRavager/BM0ORFQ0.png"
	DisableFullBright
}

BrightMap Sprite 0ORFR0
{
	Map "brightmaps/monsters/ObsidianRavager/BM0ORFR0.png"
	DisableFullBright
}

BrightMap Sprite 0ORFS0
{
	Map "brightmaps/monsters/ObsidianRavager/BM0ORFS0.png"
	DisableFullBright
}

BrightMap Sprite 0ORFT0
{
	Map "brightmaps/monsters/ObsidianRavager/BM0ORFT0.png"
	DisableFullBright
}

BrightMap Sprite V02AA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV02AD0.png"
	DisableFullBright
}

BrightMap Sprite V02AB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV02AD0.png"
	DisableFullBright
}

BrightMap Sprite V02AC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV02AD0.png"
	DisableFullBright
}

BrightMap Sprite V02AD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV02AD0.png"
	DisableFullBright
}

BrightMap Sprite V02DA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV02DD0.png"
	DisableFullBright
}

BrightMap Sprite V02DB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV02DD0.png"
	DisableFullBright
}

BrightMap Sprite V02DC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV02DD0.png"
	DisableFullBright
}

BrightMap Sprite V02DD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV02DD0.png"
	DisableFullBright
}

BrightMap Sprite V03AA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03AD0.png"
	DisableFullBright
}

BrightMap Sprite V03AB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03AD0.png"
	DisableFullBright
}

BrightMap Sprite V03AC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03AD0.png"
	DisableFullBright
}

BrightMap Sprite V03AD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03AD0.png"
	DisableFullBright
}

BrightMap Sprite V03BA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03BD0.png"
	DisableFullBright
}

BrightMap Sprite V03BB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03BD0.png"
	DisableFullBright
}

BrightMap Sprite V03BC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03BD0.png"
	DisableFullBright
}

BrightMap Sprite V03BD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03BD0.png"
	DisableFullBright
}

BrightMap Sprite V03CA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03CD0.png"
	DisableFullBright
}

BrightMap Sprite V03CB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03CD0.png"
	DisableFullBright
}

BrightMap Sprite V03CC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03CD0.png"
	DisableFullBright
}

BrightMap Sprite V03CD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03CD0.png"
	DisableFullBright
}

BrightMap Sprite V03DA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03DD0.png"
	DisableFullBright
}

BrightMap Sprite V03DB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03DD0.png"
	DisableFullBright
}

BrightMap Sprite V03DC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03DD0.png"
	DisableFullBright
}

BrightMap Sprite V03DD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV03DD0.png"
	DisableFullBright
}

BrightMap Sprite V04AA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04AD0.png"
	DisableFullBright
}

BrightMap Sprite V04AB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04AD0.png"
	DisableFullBright
}

BrightMap Sprite V04AC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04AD0.png"
	DisableFullBright
}

BrightMap Sprite V04AD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04AD0.png"
	DisableFullBright
}

BrightMap Sprite V04BA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04BD0.png"
	DisableFullBright
}

BrightMap Sprite V04BB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04BD0.png"
	DisableFullBright
}

BrightMap Sprite V04BC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04BD0.png"
	DisableFullBright
}

BrightMap Sprite V04BD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04BD0.png"
	DisableFullBright
}

BrightMap Sprite V04CA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04CD0.png"
	DisableFullBright
}

BrightMap Sprite V04CB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04CD0.png"
	DisableFullBright
}

BrightMap Sprite V04CC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04CD0.png"
	DisableFullBright
}

BrightMap Sprite V04CD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04CD0.png"
	DisableFullBright
}

BrightMap Sprite V04DA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04DD0.png"
	DisableFullBright
}

BrightMap Sprite V04DB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04DD0.png"
	DisableFullBright
}

BrightMap Sprite V04DC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04DD0.png"
	DisableFullBright
}

BrightMap Sprite V04DD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV04DD0.png"
	DisableFullBright
}

BrightMap Sprite V05AA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV05AA0.png"
	DisableFullBright
}

BrightMap Sprite V05AB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV05AB0.png"
	DisableFullBright
}

BrightMap Sprite V05AC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV05AC0.png"
	DisableFullBright
}

BrightMap Sprite V05AD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV05AD0.png"
	DisableFullBright
}

BrightMap Sprite V06AA0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV06AA0.png"
}

BrightMap Sprite V06AB0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV06AB0.png"
}

BrightMap Sprite V06AC0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV06AC0.png"
}

BrightMap Sprite V06AD0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV06AD0.png"
}

BrightMap Sprite V06AE0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV06AE0.png"
}

BrightMap Sprite V06AF0
{
	Map "brightmaps/monsters/ObsidianRavager/BMV06AF0.png"
}

BrightMap Sprite V07AA0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AA0.png" DisableFullBright }
BrightMap Sprite V07AB0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AB0.png" DisableFullBright }
BrightMap Sprite V07AC0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AC0.png" DisableFullBright }
BrightMap Sprite V07AD0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AD0.png" DisableFullBright }
BrightMap Sprite V07AE0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AE0.png" DisableFullBright }
BrightMap Sprite V07AF0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AF0.png" DisableFullBright }
BrightMap Sprite V07AG0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AG0.png" DisableFullBright }
BrightMap Sprite V07AH0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AH0.png" DisableFullBright }
BrightMap Sprite V07AI0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AI0.png" DisableFullBright }
BrightMap Sprite V07AJ0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AJ0.png" DisableFullBright }
BrightMap Sprite V07AK0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AK0.png" DisableFullBright }
BrightMap Sprite V07AL0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AL0.png" DisableFullBright }
BrightMap Sprite V07AM0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AM0.png" DisableFullBright }
BrightMap Sprite V07AN0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AN0.png" DisableFullBright }
BrightMap Sprite V07AO0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AO0.png" DisableFullBright }
BrightMap Sprite V07AP0 { MAP "brightmaps/Monsters/ObsidianRavager/BMV07AP0.png" DisableFullBright }