// Shiny Nash Gore (PBR): Nash Muhandes (base), generic name guy (normal/spec maps), Ibis Paint X.

Material Texture "GRAPHICS/PB2022/ShinyNashGore/BloodSpot/bsplat1.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat1_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat1_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/BloodSpot/bsplat2.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat2_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat2_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/BloodSpot/bsplat3.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat3_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat3_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/BloodSpot/bsplat4.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat4_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat4_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/BloodSpot/bsplat_small1.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat_small1_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat_small1_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/BloodSpot/bsplat_small2.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat_small2_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat_small2_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/BloodSpot/bsplat_small3.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat_small3_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat_small3_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/BloodSpot/bsplat_small4.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat_small4_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat_small4_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bsplat5.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat5_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat5_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bsplat6.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat6_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat6_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bsplat_small5.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat_small5_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat_small5_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bsplat_small6.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat_small6_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat_small6_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bsplat_small7.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat_small7_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat_small7_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bsplat_small8.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bsplat_small8_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bsplat_small8_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bdropl1.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bdropl1_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bdropl1_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bdropl2.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bdropl2_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bdropl2_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bdropl3.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bdropl3_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bdropl3_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bdropl4.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bdropl4_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/bdropl4_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/decals/bdrip.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/bdrip_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/genericspecular_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/CorpseBlood/CorpseBlood01.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/CorpseBlood01_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/CorpseBlood01_s.png"
	Glossiness 100
	SpecularLevel 50
}

Material Texture "GRAPHICS/PB2022/ShinyNashGore/Footprint/Footprint01.png"
{
	Normal "materials/pb2022/shiny_nashgore/normalmaps/Footprint01_n.png"
	Specular "materials/pb2022/shiny_nashgore/specularmaps/Footprint01_s.png"
	Glossiness 100
	SpecularLevel 50
}
