fader PB_PortalFastFader
{
	decaystart 0.029
	decaytime 0
}
fader PB_PortalInstantFader
{
	decaystart 0
	decaytime 0
}
decal PortalTestDecal 300
{
	animator PB_PortalInstantFader
}decal CameraDecal100 100
{
    pic PORTX100
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal100 100
{
    pic PORTX100
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal101 101
{
    pic PORTX101
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal101 101
{
    pic PORTX101
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal102 102
{
    pic PORTX102
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal102 102
{
    pic PORTX102
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal103 103
{
    pic PORTX103
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal103 103
{
    pic PORTX103
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal104 104
{
    pic PORTX104
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal104 104
{
    pic PORTX104
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal105 105
{
    pic PORTX105
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal105 105
{
    pic PORTX105
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal106 106
{
    pic PORTX106
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal106 106
{
    pic PORTX106
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal107 107
{
    pic PORTX107
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal107 107
{
    pic PORTX107
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal200 200
{
    pic PORTX200
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal200 200
{
    pic PORTX200
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal201 201
{
    pic PORTX201
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal201 201
{
    pic PORTX201
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal202 202
{
    pic PORTX202
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal202 202
{
    pic PORTX202
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal203 203
{
    pic PORTX203
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal203 203
{
    pic PORTX203
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal204 204
{
    pic PORTX204
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal204 204
{
    pic PORTX204
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal205 205
{
    pic PORTX205
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal205 205
{
    pic PORTX205
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal206 206
{
    pic PORTX206
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal206 206
{
    pic PORTX206
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}decal CameraDecal207 207
{
    pic PORTX207
    x-scale 0.25
    y-scale 0.25
    flipy
    animator PB_PortalFastFader
    fullbright
}
decal SCameraDecal207 207
{
    pic PORTX207
    x-scale 0.25
    y-scale 0.25
    animator PB_PortalFastFader
    fullbright
}
