Class EternalArachno : Arachnotron
{
	Default
	{
	  Health 1000;
	  Radius 64;
	  Height 64;
	  Mass 600;
	  Speed 12;
	  PainChance 128;
	  Monster;
	  +FLOORCLIP;
	  +BOSSDEATH;
	  MeleeRange 70;
	  SeeSound "EternalArachno/sight";
	  PainSound "EternalArachno/pain";
	  DeathSound "EternalArachno/death";
	  ActiveSound "EternalArachno/active";
	  Obituary "$OB_BABY";
	  BloodType "NashGoreBlood", "NashGoreBlood", "NashGoreBlood";
	  BloodColor "Blue";
	  Scale .40;
	}
  States
  {
  Spawn:
    ERAC A 10 A_Look;
    Loop;
	
 See:
  ARAW A 3 A_PlaySound("EternalArachno/walk", CHAN_BODY);
  ARAW BCDEFGH 1 A_Chase();
  ARAW I 3 A_PlaySound("EternalArachno/walk", CHAN_BODY);
  ARAW JKLMNO 1 A_Chase();
  Loop;
	
  Melee: 
    ARAM A 1 A_FaceTarget();
	ARAM B 1 A_CustomMeleeAttack(random(1, 10) * 6, "skeleton/melee");
	ARAM CDEFGHIJ 2;
    Goto Melee2; 
	
  Melee2: 
    ARAM KLMNOPQRS 2;
    Goto See;
	
 Missile:
    TNT1 A 0 A_Jump(96, "Missile3"); // choose variant

    ARAS A 1 A_FaceTarget();
    ARAS BCDEFGHIJK 1;
    Goto Missile2;
	
  Missile2:
	ARAS M 2 BRIGHT A_CustomMissile("EnemyPlasmaBall",100,0,0,0);
	ARAS K 1 A_FaceTarget();
	ARAS K 5;
	ARAS M 2 BRIGHT A_CustomMissile("eternalball",100,0,0,0);
	ARAS M 1 A_FaceTarget();
	ARAS K 5;
	ARAS M 2 BRIGHT A_CustomMissile("EnemyPlasmaBall",100,0,0,0);
	ARAS K 1 A_FaceTarget();
	ARAS K 5;
	ARAS M 2 BRIGHT A_CustomMissile("eternalball",100,0,0,0);
	ARAS M 1 A_FaceTarget();
	ARAS K 5;
	ARAS M 2 BRIGHT A_CustomMissile("EnemyPlasmaBall",100,0,0,0);
	ARAS M 1 A_FaceTarget();
	Goto See;
	
    Missile3:
		ARAS K 1 A_FaceTarget();
		ARAS K 5;
		ARAS M 0 BRIGHT{
		A_CustomMissile("SP_GaussTrailSiegeAOE",100,0,0,0);
		A_CustomMissile("EternalBlast",100, 0, 0, 0);
		}
		ARAS K 1 A_FaceTarget();
		Goto See;
		
  Pain:
    ERAC A 3;
    ERAC A 3 A_Pain;
    Goto See;
  Death:
    ARDA A 3 A_Scream;
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("PB_Brains4Blue", 32, 0, random (0, 360), 2, random (0, 160));
    TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 32, 20, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 32, 20, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));	
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAAAA 0 A_CustomMissile ("SmallBrainPiece", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	ARDA BCDEFGHIJKLMNOP 3;
   ARDA QRSTUVWXYZ 2;
    TNT1 A 0 A_NoBlocking;
	TNT1 A 0 A_SpawnItem ("BlueBloodPool", 1);
    ARDB ABCDE 2;
    ARDB F -1 A_BossDeath;
    Stop;
	
	Death.ExecutionPinata:
	ERAC A 28;
	TNT1 A 0
	{
		if (Random(0,99) < 40)
		{
			A_PlaySound("GloryPunch/Kill", CHAN_AUTO, 2.0);
		}

		A_SpawnItemEx("GloryMedPinataSpawn",0,0,Height / 2,random(0,8),0,random(0,8),random(0,360));
	}
    Goto XDeath;
	
 Death.Execution:
 ERAC A 28;   
    Goto XDeath;
  XDeath:
    ARDA A 3 A_Scream;
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("PB_Brains4Blue", 32, 0, random (0, 360), 2, random (0, 160));
    TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 32, 20, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 32, 20, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItem("BloodSplasher3");
	   TNT1 AAAAAAAAAAAAAAA 0 A_SpawnItem("PB_SuperWallRedBlood");
         TNT1 AAAAAAAAA 0 A_SpawnItem("CeilBloodLauncherLong");
	TNT1 A 0 {
	A_SpawnItem ("PB_SuperWallRedBlood");
	A_SpawnItem ("PB_SuperWallRedBlood");
	A_SpawnItem ("PB_SuperWallRedBlood");
	A_SpawnItem ("PB_SuperWallRedBlood");
	A_SpawnItemEX ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
	A_SpawnItemEX ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
	A_SpawnItemEX ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
	A_SpawnItemEX ("PB_BloodmistLarge", 40, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (30, 90));
	}
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));	
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAAAAAAAA 0 A_CustomMissile ("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAAAA 0 A_CustomMissile ("SmallBrainPiece", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	ARDA BCDEFGHIJKLMNOP 3;
   ARDA QRSTUVWXYZ 2;
    TNT1 A 0 A_NoBlocking;
	TNT1 A 0 A_SpawnItem ("BlueBloodPool", 1);
    ARDB ABCDE 2;
    ARDB F -1 A_BossDeath;
    Stop;
	
  Raise:
    ARDB E 5;
    ARDA ABCDEFGHIJKLMNOPQRSTUVWXYZ 1;
    ARDB ABCDE 1;
    Goto See;
  }
}

Class eternalball : PB_SpecialCacoDemonBall2
{
	Default
	{
	+SEEKERMISSILE;
	+RANDOMIZE;
	+RIPPER;
	Speed 35;
	FastSpeed 25;
	}
	
	States {
		Spawn:
		TNT1 A 0 NoDelay A_Jump(128,"Homing");
		0CB0 A 1 BRIGHT {
				A_Startsound("CacoBallLoop", CHAN_BODY , CHANF_LOOP, 1);
			}
		Homing:
			TNT1 A 0 Bright A_SeekerMissile(45,45,SMF_PRECISE|SMF_LOOK);
			0CB0 BCDEFA 2 BRIGHT {
				A_Weave(0,5,0,2);
				A_SpawnProjectile ("RailGunTrailSpark", 0, 0, random (0, 360), CMF_AIMDIRECTION|CMF_ABSOLUTEPITCH|CMF_OFFSETPITCH|CMF_BADPITCH|CMF_SAVEPITCH, random (0, 360));
			}
			Loop;
	}
	
}
		
Class EternalBlast : FastProjectile
{
	default
	{
		Radius 12;
		Height 16;
		Damage 20;
		Renderstyle "Add";
		+RIPPER;
		-CANNOTPUSH;
		+NODAMAGETHRUST;
		+EXTREMEDEATH;
		+FORCERADIUSDMG;
		DamageType "Incinerate";
		MissileType "LaserTrail"; //this is actually not needed anymore
		MissileHeight 10;
		//SeeSound "weapons/railgun/laser_big_4";
		Speed 65;
		Translation "112:127=168:183", "160:175=168:183", "192:207=168:183";
		Scale .30;
	}
	states
	{
		Spawn:
		See:
			TNT1 A 0 NoDelay A_startsound("weapons/railgun/laser_big_4",CHAN_AUTO,attenuation:0);
		Fly:
			TNT1 A 4;
			Loop;
		Death:
			TNT1 A 0;
			TNT1 AAA 0 A_SpawnItemEx("ObeliskTrailSpark", random(19,-19), random(19,-19), random(19,-19), 0, 0, 0, 0, 128, 0);
			TNT1 A 0 A_SpawnItemEx("ObeliskExplode",0,0,0,0,0,0,0,128,0);
			TNT1 A 0 A_Explode(200,250,0,1);
			TNT1 A 0 A_SpawnItem("WhiteShockwave");
			TNT1 A 0 A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAA 0 A_Spawnprojectile ("FireworkSFXType2", 0, 0, random (0, 360), 2, random (-60, -30));
			EXPL AAA 0 A_Spawnprojectile ("FlamethrowerFireParticles", 6, 0, random (0, 360), 2, random (-90,0));
			TNT1 AAA 0 A_Spawnprojectile ("ExplosionParticleHeavy", 0, 0, random (0, 360), 2, random (-180,0));
			EXPL A 0 Radius_Quake(3, 120, 0, 120, 0);
			BEXP B 0 BRIGHT A_Scream();
			X001 ABCDEFGHIJKLMNOPQRSTUVWXYZ 1 BRIGHT;
			TNT1 AAA 10 A_Spawnprojectile("BigBlackSmoke", 0, 0, random (0, 360), 2, random (40, 160));
			stop;
	}
	
	override void Effect()
	{
		//copied from gzdoom.pk3/Zscript/Actors/Shared/Fastprojectile.zs
		//basically this is made to replace the actors trail for a lighter version with textured particles
		double hitz = pos.z - 8;
		if (hitz < floorz)
		{
			hitz = floorz;
		}
		// Do not clip this offset to the floor.
		hitz += MissileHeight;
		
		SpawnLaserTrail((pos.xy, hitz));
	}
	
	void SpawnLaserTrail(vector3 where)
	{
		FSpawnParticleParams LaserGun;
		LaserGun.Texture = TexMan.CheckForTexture("YAE5A0");
		LaserGun.Style = STYLE_ADD;
		LaserGun.Color1 = "FFFFFF";
		LaserGun.Flags =SPF_FULLBRIGHT|SPF_NOTIMEFREEZE;
		LaserGun.StartAlpha = 1.0;
		LaserGun.FadeStep = 0.25;
		//LaserGun.Size = 220;
		LaserGun.Size = 60;
		LaserGun.SizeStep = -10;
		LaserGun.Lifetime = 10; 
		LaserGun.Pos = where;
		Level.SpawnParticle(LaserGun);
	}
}