class PBCF_FriendlyDeployableBase : Actor
{
	override int DamageMobj(Actor inflictor, Actor source, int damage, Name mod, int flags, double angle)
	{
		if (source && source.player)
			return 0;
		if (inflictor && inflictor.player)
			return 0;
		if (inflictor && inflictor.target && inflictor.target.player)
			return 0;
		if (source && source.target && source.target.player)
			return 0;
		return Super.DamageMobj(inflictor, source, damage, mod, flags, angle);
	}
}
