// BDv22 mist (`P22M*` sprites).
class BDv22GoreMist : PB_Bloodmist
{
	Default
	{
		scale 0.32;
	}

	States
	{
		Spawn:
			P22M ABCDEFGH 2;
			P22M HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 1 A_FadeOut(0.005);
			Stop;
		Death:
			TNT1 A 0 A_StartSound("blooddrop");
			TNT1 A 0 A_CheckFloor("Disappear");
			P22M HHHHHHHHHH 1 A_FadeOut(0.1);
			Stop;
		Disappear:
			TNT1 A 2;
			Stop;
	}
}
