#library "Shield_saw"
#include "zcommon.acs"

Script "Shield_saw" (void)
{
	str weapon = GetWeapon();
	if (StrICmp(weapon, "TheShieldSaw"))
	{
		SetPlayerProperty(0, 1, PROP_INSTANTWEAPONSWITCH);
		GiveInventory("TheShieldSaw", 1);
		SetWeapon("TheShieldSaw");
		While (CheckInventory("ShieldSaw_token"))
			Delay(1);
		SetWeapon(weapon);
		TakeInventory("TheShieldSaw", 1);
		SetPlayerProperty(0, 0, PROP_INSTANTWEAPONSWITCH);
	}
}